In [3]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.2
NumPy version: 2.4.4

In [4]:
qs = pd.read_csv("Data2/QS2024.csv",encoding="latin1")
the = pd.read_csv("Data2/QS2025.csv",encoding="latin1")

In [3]:
qs.head()

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

In [4]:
the.head()

,ï»¿2024 RANK,2023 RANK,Institution Name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Faculty Rank,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE
0,rank display,rank display2,institution,location code,location,size,focus,research,age band,status,...,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,SUS SCORE,SUS RANK,Overall Score
1,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,56,88.2,128,94.3,58,100,4,95.2,51,100.0
2,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,64,95.8,85,99.9,7,100,6,97.3,33=,99.2
3,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,110,98.2,60,100.0,1,100,3,97.8,26=,98.9
4,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,210,66.8,223,100.0,5,100,1,96.7,39,98.3

In [5]:
the.rename(columns={
    "Institution Name":"Institution_Name"
}, inplace=True)

In [6]:
times = pd.read_csv("Data2/timesData.csv")

shanghai = pd.read_csv("Data2/shanghaiData.csv")

In [8]:
times.head()

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011

In [9]:
shanghai.head()

,world_rank,university_name,national_rank,total_score,alumni,award,hici,ns,pub,pcp,year
0,1,Harvard University,1,100.0,100.0,100.0,100.0,100.0,100.0,72.4,2005
1,2,University of Cambridge,1,73.6,99.8,93.4,53.3,56.6,70.9,66.9,2005
2,3,Stanford University,2,73.4,41.1,72.2,88.5,70.9,72.3,65.0,2005
3,4,"University of California, Berkeley",3,72.8,71.8,76.0,69.4,73.9,72.2,52.7,2005
4,5,Massachusetts Institute of Technology (MIT),4,70.1,74.0,80.6,66.7,65.8,64.3,53.0,2005

In [13]:
qs.rename(columns={
    "Institution_Name": "university_name"
}, inplace=True)

the.rename(columns={
    "Institution Name": "university_name"
}, inplace=True)

In [14]:
the.head()

,ï»¿2024 RANK,2023 RANK,university_name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Faculty Rank,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE
0,rank display,rank display2,institution,location code,location,size,focus,research,age band,status,...,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,SUS SCORE,SUS RANK,Overall Score
1,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,56,88.2,128,94.3,58,100,4,95.2,51,100.0
2,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,64,95.8,85,99.9,7,100,6,97.3,33=,99.2
3,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,110,98.2,60,100.0,1,100,3,97.8,26=,98.9
4,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,210,66.8,223,100.0,5,100,1,96.7,39,98.3

In [15]:
qs.head()

,RANK_2025,RANK_2024,university_name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

In [16]:
for df in [qs, the, times, shanghai]:
    df["university_name"] = (
        df["university_name"]
        .str.strip()
        .str.lower()
    )

In [17]:
merged = pd.merge(
    qs,
    the,
    on="university_name",
    how="outer"
)

In [18]:
merged = pd.merge(
    merged,
    times,
    on="university_name",
    how="outer"
)

In [19]:
merged = pd.merge(
    merged,
    shanghai,
    on="university_name",
    how="outer"
)

In [20]:
merged.head()

,RANK_2025,RANK_2024,university_name,Location,Region,SIZE_x,FOCUS_x,RES._x,STATUS_x,Academic_Reputation_Score,...,world_rank_y,national_rank,total_score_y,alumni,award,hici,ns,pub,pcp,year_y
0,306,336,aalborg university,Denmark,Europe,L,FC,VH,A,19.9,...,401-500,5,NaN,0.0,0.0,12.2,3.4,27.6,15.2,2014.0
1,306,336,aalborg university,Denmark,Europe,L,FC,VH,A,19.9,...,301-400,5,NaN,0.0,0.0,11.2,4.6,30.4,16.8,2015.0
2,306,336,aalborg university,Denmark,Europe,L,FC,VH,A,19.9,...,401-500,5,NaN,0.0,0.0,12.2,3.4,27.6,15.2,2014.0
3,306,336,aalborg university,Denmark,Europe,L,FC,VH,A,19.9,...,301-400,5,NaN,0.0,0.0,11.2,4.6,30.4,16.8,2015.0
4,306,336,aalborg university,Denmark,Europe,L,FC,VH,A,19.9,...,401-500,5,NaN,0.0,0.0,12.2,3.4,27.6,15.2,2014.0

In [21]:
print("Rows:", merged.shape)

Rows: (17661, 79)

In [22]:
print("Duplicate university names:",
      merged["university_name"].duplicated().sum())

Duplicate university names: 15364

In [23]:
times.columns.tolist()

['world_rank',
 'university_name',
 'country',
 'teaching',
 'international',
 'research',
 'citations',
 'income',
 'total_score',
 'num_students',
 'student_staff_ratio',
 'international_students',
 'female_male_ratio',
 'year']

In [24]:
merged.columns.tolist()

['RANK_2025',
 'RANK_2024',
 'university_name',
 'Location',
 'Region',
 'SIZE_x',
 'FOCUS_x',
 'RES._x',
 'STATUS_x',
 'Academic_Reputation_Score',
 'Academic_Reputation_Rank',
 'Employer_Reputation_Score',
 'Employer_Reputation_Rank',
 'Faculty_Student_Score',
 'Faculty_Student_Rank',
 'Citations_per_Faculty_Score',
 'Citations_per_Faculty_Rank',
 'International_Faculty_Score',
 'International_Faculty_Rank',
 'International_Students_Score',
 'International_Students_Rank',
 'International_Research_Network_Score',
 'International_Research_Network_Rank',
 'Employment_Outcomes_Score',
 'Employment_Outcomes_Rank',
 'Sustainability_Score',
 'Sustainability_Rank',
 'Overall_Score',
 'ï»¿2024 RANK',
 '2023 RANK',
 'Country Code',
 'Country',
 'SIZE_y',
 'FOCUS_y',
 'RES._y',
 'AGE',
 'STATUS_y',
 'Academic Reputation Score',
 'Academic Reputation Rank',
 'Employer Reputation Score',
 'Employer Reputation Rank',
 'Faculty Student Score',
 'Faculty Student Rank',
 'Citations per Faculty Score',
 'Citations per Faculty Rank',
 'International Faculty Score',
 'International Faculty Rank',
 'International Students Score',
 'International Students Rank',
 'International Research Network Score',
 'International Research Network Rank',
 'Employment Outcomes Score',
 'Employment Outcomes Rank',
 'Sustainability Score',
 'Sustainability Rank',
 'Overall SCORE',
 'world_rank_x',
 'country',
 'teaching',
 'international',
 'research',
 'citations',
 'income',
 'total_score_x',
 'num_students',
 'student_staff_ratio',
 'international_students',
 'female_male_ratio',
 'year_x',
 'world_rank_y',
 'national_rank',
 'total_score_y',
 'alumni',
 'award',
 'hici',
 'ns',
 'pub',
 'pcp',
 'year_y']

In [25]:
merged.shape

(17661, 79)

In [26]:
times.shape

(2603, 14)

In [27]:
print("teaching" in merged.columns)
print("international" in merged.columns)
print("research" in merged.columns)
print("num_students" in merged.columns)

True
True
True
True

In [28]:
required = [
    "university_name",
    "world_rank",
    "national_rank",
    "overall_score",
    "academic_reputation_score",
    "employer_reputation_score",
    "citations_score",
    "publications_count",
    "research",
    "international",
    "num_students",
    "student_staff_ratio",
    "international_students",
    "female_male_ratio"
]

for col in required:
    print(f"{col:<35} {'✅ Present' if col in merged.columns else '❌ Missing'}")

university_name                     ✅ Present
world_rank                          ❌ Missing
national_rank                       ✅ Present
overall_score                       ❌ Missing
academic_reputation_score           ❌ Missing
employer_reputation_score           ❌ Missing
citations_score                     ❌ Missing
publications_count                  ❌ Missing
research                            ✅ Present
international                       ✅ Present
num_students                        ✅ Present
student_staff_ratio                 ✅ Present
international_students              ✅ Present
female_male_ratio                   ✅ Present

In [30]:
merged.to_csv("Data2/Merged_Raw_Dataset.csv", index=False)