In [2]:
import pandas as pd

# Load files
master = pd.read_csv("master_common_universities.csv")
qs = pd.read_csv("qs2026_clean.csv")
the = pd.read_csv("the_clean.csv")
cwur = pd.read_csv("cwur_clean.csv")

# Standardize names
for df in [master, qs, the, cwur]:
    df["clean_name"] = (
        df["University_Name"]
        .astype(str)
        .str.lower()
        .str.strip()
    )

# Merge QS
merged = master.merge(
    qs,
    on="clean_name",
    how="left",
    suffixes=("", "_qs")
)

# Merge THE
merged = merged.merge(
    the,
    on="clean_name",
    how="left",
    suffixes=("", "_the")
)

# Merge CWUR
merged = merged.merge(
    cwur,
    on="clean_name",
    how="left",
    suffixes=("", "_cwur")
)

print("Rows:", merged.shape[0])
print("Columns:", merged.shape[1])

merged.to_csv(
    "master_university_dataset.csv",
    index=False
)

print("master_university_dataset.csv created successfully!")

Rows: 480
Columns: 46
master_university_dataset.csv created successfully!

In [3]:
merged.head()

,University_Name,Match_Type,clean_name,University_Name_qs,Country,Region,Year,QS_Rank,National_Rank,QS_Overall_Score,...,Year_cwur,CWUR_Rank,Quality_of_Education,Alumni_Employment,Publications,Influence,Patents,Std_Country_cwur,Std_University_Name_cwur,Base_Match_Score_cwur
0,aalborg university,Exact,aalborg university,Aalborg University,Denmark,Europe,2026.0,306.0,5.0,44.9,...,2015.0,565.0,367.0,439.0,596.0,660.0,401.0,Denmark,Aalborg University,100.0
1,aalto university,Exact,aalto university,Aalto University,Finland,Europe,2026.0,114.0,1.0,66.3,...,2015.0,421.0,367.0,224.0,336.0,403.0,246.0,Finland,Aalto University,100.0
2,aarhus university,Exact,aarhus university,Aarhus University,Denmark,Europe,2026.0,131.0,3.0,64.3,...,2015.0,122.0,310.0,165.0,91.0,81.0,154.0,Denmark,Aarhus University,100.0
3,aberystwyth university,Exact,aberystwyth university,Aberystwyth University,United Kingdom,Europe,2026.0,741.0,63.0,NaN,...,2015.0,814.0,367.0,567.0,842.0,552.0,607.0,United Kingdom,Aberystwyth University,100.0
4,aixmarseille university,Exact,aixmarseille university,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
merged.isnull().sum().sort_values(ascending=False).head(20)

Total_Score                 371
QS_Overall_Score            146
Industry_Income             101
Year_cwur                    93
CWUR_Rank                    93
University_Name_cwur         93
Base_Match_Score_cwur        93
Std_Country_cwur             93
Std_University_Name_cwur     93
Influence                    93
Alumni_Employment            93
Publications                 93
Country_cwur                 93
Quality_of_Education         93
Patents                      93
Teaching_Score               88
THE_Rank                     88
Year_the                     88
Citation_Score               88
Country_the                  88
dtype: int64

In [5]:
print("Missing QS:", merged["University_Name_qs"].isna().sum())
print("Missing THE:", merged["University_Name_the"].isna().sum())
print("Missing CWUR:", merged["University_Name_cwur"].isna().sum())

Missing QS: 52
Missing THE: 88
Missing CWUR: 93

In [6]:
merged[
    merged["University_Name_qs"].isna()
][["University_Name"]].head(20)

                                   University_Name
4                          aixmarseille university
14                              barilan university
37                             chungang university
82                           heriotwatt university
150                 national sun yatsen university
174                      queens university belfast
200                          sun yatsen university
207        technion israel institute of technology
246                 university of california davis
247                university of california irvine
248             university of california riverside
249            university of california santa cruz
254  university of chemistry and technology prague
289      university of illinois at urbanachampaign
296                     university of kwazulunatal
306        university of maryland baltimore county
307            university of maryland college park
315               university of naples federico ii
377                 university of wisconsinmadison
390              washington university in st louis

In [7]:
the2023 = pd.read_csv("the2023_clean.csv")

the2023.columns

Index(['University_Name', 'Country', 'Year', 'THE2023_Rank', 'Total_Students',
       'Faculty_Student_Ratio_2023', 'Faculty_Count',
       'International_Student_Ratio_2023', 'International_Students_Count',
       'Gender_Ratio', 'Female_Percentage', 'Male_Percentage',
       'Teaching_Score_2023', 'Research_Score_2023', 'Citations_Score_2023',
       'Industry_Income_Score_2023', 'International_Outlook_Score_2023',
       'Overall_Score_2023', 'Std_Country', 'Std_University_Name',
       'Base_Match_Score'],
      dtype='object')

In [8]:
import pandas as pd

# Load files
master = pd.read_csv("master_university_dataset.csv")
the2023 = pd.read_csv("the2023_clean.csv")

# Create clean names
master["clean_name"] = (
    master["University_Name"]
    .astype(str)
    .str.lower()
    .str.strip()
)

the2023["clean_name"] = (
    the2023["University_Name"]
    .astype(str)
    .str.lower()
    .str.strip()
)

# Merge
master_final = master.merge(
    the2023,
    on="clean_name",
    how="left",
    suffixes=("", "_the2023")
)

print("Rows:", master_final.shape[0])
print("Columns:", master_final.shape[1])

master_final.to_csv(
    "master_dataset_with_students.csv",
    index=False
)

print("master_dataset_with_students.csv created successfully!")

Rows: 480
Columns: 67
master_dataset_with_students.csv created successfully!

In [9]:
print(
    "Missing Student Data:",
    master_final["Total_Students"].isna().sum()
)

Missing Student Data: 110

In [10]:
important_cols = [
    "QS_Rank",
    "THE_Rank",
    "CWUR_Rank",
    "QS_Overall_Score",
    "Teaching_Score",
    "Research_Score",
    "Citation_Score",
    "Total_Students",
    "Faculty_Count",
    "International_Students_Count"
]

for col in important_cols:
    missing = master_final[col].isna().sum()
    print(f"{col}: {missing}")

QS_Rank: 52
THE_Rank: 88
CWUR_Rank: 93
QS_Overall_Score: 146
Teaching_Score: 88
Research_Score: 88
Citation_Score: 88
Total_Students: 110
Faculty_Count: 110
International_Students_Count: 110

In [11]:
openalex_input = master_final[["University_Name"]].copy()

openalex_input.to_csv(
    "openalex_university_list.csv",
    index=False
)

print("Universities:", len(openalex_input))
openalex_input.head()

Universities: 480

           University_Name
0       aalborg university
1         aalto university
2        aarhus university
3   aberystwyth university
4  aixmarseille university

In [12]:
!pip install requests pandas tqdm

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
import pandas as pd
import requests
import time
from tqdm import tqdm

universities = pd.read_csv("openalex_university_list.csv")

results = []

for uni in tqdm(universities["University_Name"]):

    try:
        url = f"https://api.openalex.org/institutions?search={uni}"

        response = requests.get(url, timeout=20)

        if response.status_code != 200:
            continue

        data = response.json()

        if len(data["results"]) == 0:
            continue

        inst = data["results"][0]

        subject_field = None

        if "topics" in inst and len(inst["topics"]) > 0:
            subject_field = inst["topics"][0].get("display_name")

        results.append({
            "University_Name": uni,
            "publications_count": inst.get("works_count"),
            "citations_count": inst.get("cited_by_count"),
            "h_index": inst.get("summary_stats", {}).get("h_index"),
            "i10_index": inst.get("summary_stats", {}).get("i10_index"),
            "subject_field": subject_field
        })

        time.sleep(0.1)

    except Exception:
        continue

openalex_df = pd.DataFrame(results)

print("Records fetched:", len(openalex_df))

openalex_df.to_csv(
    "openalex_research_metrics.csv",
    index=False
)

print("Saved: openalex_research_metrics.csv")

100%|██████████| 480/480 [00:52<00:00,  9.19it/s]

Records fetched: 96
Saved: openalex_research_metrics.csv

In [14]:
openalex_df.head()

,University_Name,publications_count,citations_count,h_index,i10_index,subject_field
0,aalborg university,113662,4508973,547,72780,Microgrid Control and Optimization
1,aalto university,64289,3474473,490,57323,Advanced Cellulose Research Studies
2,aarhus university,224568,12761968,859,177239,"Education, Healthcare and Sociology Research"
3,aberystwyth university,27895,1648938,390,24220,Geology and Paleoclimatology Research
4,ajou university,43374,2182909,333,45199,Asthma and respiratory diseases

In [15]:
print(len(openalex_df))

96

In [16]:
input_df = pd.read_csv("openalex_university_list.csv")

found = set(openalex_df["University_Name"])

missing = input_df[
    ~input_df["University_Name"].isin(found)
]

print("Missing universities:", len(missing))
missing.head(20)

Missing universities: 384

                   University_Name
4          aixmarseille university
14              barilan university
37             chungang university
82           heriotwatt university
100               jilin university
101       johns hopkins university
102            kanazawa university
103        kansas state university
104               keele university
105                keio university
106          kent state university
107           king saud university
108                kobe university
109              konkuk university
110               korea university
111            kumamoto university
112               kyoto university
113           kyung hee university
114  kyungpook national university
115              kyushu university

In [17]:
print("Input Universities:", 480)
print("Matched Universities:", len(openalex_df))
print("Success Rate:", round(len(openalex_df)/480*100,2), "%")

Input Universities: 480
Matched Universities: 96
Success Rate: 20.0 %

In [18]:
input_df = pd.read_csv("openalex_university_list.csv")

found = set(openalex_df["University_Name"])

missing = input_df[
    ~input_df["University_Name"].isin(found)
]

print("Missing universities:", len(missing))
missing.head(20)

Missing universities: 384

                   University_Name
4          aixmarseille university
14              barilan university
37             chungang university
82           heriotwatt university
100               jilin university
101       johns hopkins university
102            kanazawa university
103        kansas state university
104               keele university
105                keio university
106          kent state university
107           king saud university
108                kobe university
109              konkuk university
110               korea university
111            kumamoto university
112               kyoto university
113           kyung hee university
114  kyungpook national university
115              kyushu university

In [19]:
# Use original QS names wherever available

openalex_input_v2 = master_final[
    ["University_Name", "University_Name_qs"]
].copy()

# Prefer QS original name
openalex_input_v2["search_name"] = openalex_input_v2[
    "University_Name_qs"
].fillna(openalex_input_v2["University_Name"])

openalex_input_v2 = openalex_input_v2[
    ["University_Name", "search_name"]
]

print("Universities:", len(openalex_input_v2))

openalex_input_v2.to_csv(
    "openalex_university_list_v2.csv",
    index=False
)

openalex_input_v2.head()

Universities: 480

           University_Name              search_name
0       aalborg university       Aalborg University
1         aalto university         Aalto University
2        aarhus university        Aarhus University
3   aberystwyth university   Aberystwyth University
4  aixmarseille university  aixmarseille university

In [20]:
openalex_input_v2.head(20)

                         University_Name                           search_name
0                     aalborg university                    Aalborg University
1                       aalto university                      Aalto University
2                      aarhus university                     Aarhus University
3                 aberystwyth university                Aberystwyth University
4                aixmarseille university               aixmarseille university
5                        ajou university                       Ajou University
6                  alexandria university                 Alexandria University
7     amirkabir university of technology    Amirkabir University of Technology
8   aristotle university of thessaloniki  Aristotle University of Thessaloniki
9               arizona state university              Arizona State University
10                      aston university                      Aston University
11                     auburn university                     Auburn University
12        australian national university        Australian National University
13                     bangor university                     Bangor University
14                    barilan university                    barilan university
15       beijing institute of technology       Beijing Institute of Technology
16                    bilkent university                    Bilkent University
17                        boston college                        Boston College
18                     boston university                     Boston University
19                   brandeis university                   Brandeis University

In [21]:
import pandas as pd
import requests
import time
from tqdm import tqdm

universities = pd.read_csv("openalex_university_list_v2.csv")

results = []

for _, row in tqdm(universities.iterrows(),
                   total=len(universities)):

    original_name = row["University_Name"]
    search_name = row["search_name"]

    try:

        url = (
            "https://api.openalex.org/institutions"
            f"?search={search_name}"
        )

        response = requests.get(url, timeout=20)

        if response.status_code != 200:
            continue

        data = response.json()

        if len(data["results"]) == 0:
            continue

        inst = data["results"][0]

        subject_field = None

        if (
            "topics" in inst
            and len(inst["topics"]) > 0
        ):
            subject_field = (
                inst["topics"][0]
                .get("display_name")
            )

        results.append({
            "University_Name": original_name,
            "Matched_Name": inst.get("display_name"),
            "publications_count": inst.get("works_count"),
            "citations_count": inst.get("cited_by_count"),
            "h_index": inst.get("summary_stats", {})
                            .get("h_index"),
            "i10_index": inst.get("summary_stats", {})
                             .get("i10_index"),
            "subject_field": subject_field
        })

        time.sleep(0.1)

    except Exception:
        continue

openalex_df_v2 = pd.DataFrame(results)

print("Records fetched:",
      len(openalex_df_v2))

openalex_df_v2.to_csv(
    "openalex_research_metrics_v2.csv",
    index=False
)

print("Saved successfully!")

100%|██████████| 480/480 [00:31<00:00, 15.48it/s]

Records fetched: 0
Saved successfully!

In [22]:
print(len(openalex_df_v2))

0

In [23]:
openalex_df_v2.head()

Empty DataFrame
Columns: []
Index: []

In [24]:
import requests

test_name = "Harvard University"

url = f"https://api.openalex.org/institutions?search={test_name}"

response = requests.get(url)

print("Status:", response.status_code)

data = response.json()

print("Keys:", data.keys())

print("Results found:", len(data.get("results", [])))

if len(data.get("results", [])) > 0:
    print("Matched:", data["results"][0]["display_name"])

Status: 429
Keys: dict_keys(['error', 'message', 'retryAfter', 'costUsd', 'dailyRemainingUsd', 'prepaidRemainingUsd', 'creditsRequired', 'creditsRemaining', 'onetimeCreditsRemaining'])
Results found: 0

In [25]:
universities = pd.read_csv("openalex_university_list_v2.csv")

print(universities.head())

test_name = universities.iloc[0]["search_name"]
print("Searching:", test_name)

url = f"https://api.openalex.org/institutions?search={test_name}"

r = requests.get(url)

print(r.status_code)

data = r.json()

print("Results:", len(data.get("results", [])))

           University_Name              search_name
0       aalborg university       Aalborg University
1         aalto university         Aalto University
2        aarhus university        Aarhus University
3   aberystwyth university   Aberystwyth University
4  aixmarseille university  aixmarseille university
Searching: Aalborg University
429
Results: 0

In [26]:
print("Total Columns:", len(master_final.columns))

for col in master_final.columns:
    print(col)

Total Columns: 67
University_Name
Match_Type
clean_name
University_Name_qs
Country
Region
Year
QS_Rank
National_Rank
QS_Overall_Score
Academic_Reputation
Employer_Reputation
Faculty_Student_Ratio
Citations_Per_Faculty
International_Faculty_Ratio
International_Students_Ratio
International_Research_Network
Employment_Outcomes
Sustainability
Std_Country
Std_University_Name
University_Name_the
Country_the
Year_the
THE_Rank
Teaching_Score
Research_Score
Citation_Score
International_Outlook
Industry_Income
Total_Score
Std_Country_the
Std_University_Name_the
Base_Match_Score
University_Name_cwur
Country_cwur
Year_cwur
CWUR_Rank
Quality_of_Education
Alumni_Employment
Publications
Influence
Patents
Std_Country_cwur
Std_University_Name_cwur
Base_Match_Score_cwur
University_Name_the2023
Country_the2023
Year_the2023
THE2023_Rank
Total_Students
Faculty_Student_Ratio_2023
Faculty_Count
International_Student_Ratio_2023
International_Students_Count
Gender_Ratio
Female_Percentage
Male_Percentage
Teaching_Score_2023
Research_Score_2023
Citations_Score_2023
Industry_Income_Score_2023
International_Outlook_Score_2023
Overall_Score_2023
Std_Country_the2023
Std_University_Name_the2023
Base_Match_Score_the2023

In [27]:
import numpy as np

final_eduvision = master_final.copy()

# Research Excellence Index
final_eduvision["Research_Excellence_Index"] = (
    0.4 * final_eduvision["Research_Score"].fillna(0) +
    0.3 * final_eduvision["Citation_Score"].fillna(0) +
    0.2 * final_eduvision["Publications"].fillna(0) +
    0.1 * final_eduvision["Influence"].fillna(0)
)

# Innovation Index
final_eduvision["Innovation_Index"] = (
    final_eduvision["Patents"].fillna(0) +
    final_eduvision["Influence"].fillna(0)
)

# Student Experience Index
final_eduvision["Student_Experience_Index"] = (
    0.4 * final_eduvision["Teaching_Score_2023"].fillna(0) +
    0.3 * final_eduvision["International_Student_Ratio_2023"].fillna(0) +
    0.3 * (100 - final_eduvision["Faculty_Student_Ratio_2023"].fillna(0))
)

# Global Reputation Index
final_eduvision["Global_Reputation_Index"] = (
    0.6 * final_eduvision["Academic_Reputation"].fillna(0) +
    0.4 * final_eduvision["Employer_Reputation"].fillna(0)
)

# Research Productivity Score
final_eduvision["Research_Productivity_Score"] = (
    final_eduvision["Publications"].fillna(0) +
    final_eduvision["Citation_Score"].fillna(0)
)

# Internationalization Score
final_eduvision["Internationalization_Score"] = (
    final_eduvision["International_Students_Ratio"].fillna(0) +
    final_eduvision["International_Faculty_Ratio"].fillna(0) +
    final_eduvision["International_Outlook"].fillna(0)
) / 3

print("New Shape:", final_eduvision.shape)

New Shape: (480, 73)

In [28]:
final_eduvision.to_csv(
    "final_eduvision_dataset.csv",
    index=False
)

print("✅ final_eduvision_dataset.csv created successfully")

✅ final_eduvision_dataset.csv created successfully

In [29]:
from google.colab import files
files.download("final_eduvision_dataset.csv")