In [6]:
# EduVision DV - Module 1

## Data Collection and Raw Master Dataset Creation

### **Objective**

###- Read all raw datasets
###- Standardize important columns
###- Merge into a raw master dataset
###- Export `master_dataset.csv`

In [9]:
from pathlib import Path
import pandas as pd
import os
import sys

# Go up one level if your notebook is in a subfolder (like 'notebooks')
# Adjust ".." to your actual path if your structure is deeper!
sys.path.append(os.path.abspath(".."))

from scripts.data_collection import load_raw_datasets, main

from scripts.data_collection import (
    load_raw_datasets,
    main
)

In [10]:
RAW_PATH = Path("../datasets/raw")
OUTPUT_PATH = Path("../datasets/final")

print("Raw Folder :", RAW_PATH)
print("Output Folder :", OUTPUT_PATH)

Raw Folder : ..\datasets\raw
Output Folder : ..\datasets\final

In [11]:
csv_files = sorted(RAW_PATH.rglob("*.csv"))

print(f"Datasets Found : {len(csv_files)}\n")

for file in csv_files:
    print(file.name)

Datasets Found : 8

2023 QS World University Rankings.csv
2024 QS World University Rankings 1.1 (For qs.com).csv
2026 QS World University Rankings.csv
QS World University Rankings 2025 (Top global universities).csv
qs-world-university-rankings-2017-to-2022-V2.csv
THE World University Rankings 2016-2026.csv
world-universities.csv
world_university_rankings_2026.csv

In [12]:
datasets = load_raw_datasets()

print(f"Loaded {len(datasets)} datasets")

Loaded 8 datasets

In [13]:
summary = pd.DataFrame({
    "Dataset": [f.name for f in csv_files],
    "Rows": [df.shape[0] for df in datasets],
    "Columns": [df.shape[1] for df in datasets]
})

summary

                                             Dataset   Rows  Columns
0              2023 QS World University Rankings.csv   1422       25
1  2024 QS World University Rankings 1.1 (For qs....   1498       25
2              2026 QS World University Rankings.csv   1501       25
3  QS World University Rankings 2025 (Top global ...   1503       25
4   qs-world-university-rankings-2017-to-2022-V2.csv   6482       25
5        THE World University Rankings 2016-2026.csv  16713       25
6                             world-universities.csv   9362       25
7                 world_university_rankings_2026.csv     57       25

In [14]:
datasets[0].head()

,University,Country,Country Code,Rank,Overall Score,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,...,Students to Staff Ratio,International Students,Female to Male Ratio,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year,Source File
0,Massachusetts Institute of Technology (MIT),United States,US,1,<NA>,100.0,100.0,100.0,100.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
1,University of Cambridge,United Kingdom,UK,2,<NA>,100.0,100.0,100.0,92.3,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
2,Stanford University,United States,US,3,<NA>,100.0,100.0,100.0,99.9,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
3,University of Oxford,United Kingdom,UK,4,<NA>,100.0,100.0,100.0,90.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
4,Harvard University,United States,US,5,<NA>,100.0,100.0,99.4,100.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings

In [16]:
all_data = load_raw_datasets()

print(f"Total datasets processed : {len(all_data)}")

master_df = pd.concat(all_data, ignore_index=True, sort=False)

print("\nMaster Dataset Created Successfully")
print(f"Rows    : {master_df.shape[0]}")
print(f"Columns : {master_df.shape[1]}")

master_df.head()

Total datasets processed : 8

Master Dataset Created Successfully
Rows    : 38538
Columns : 25

,University,Country,Country Code,Rank,Overall Score,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,...,Students to Staff Ratio,International Students,Female to Male Ratio,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year,Source File
0,Massachusetts Institute of Technology (MIT),United States,US,1,<NA>,100.0,100.0,100.0,100.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
1,University of Cambridge,United Kingdom,UK,2,<NA>,100.0,100.0,100.0,92.3,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
2,Stanford University,United States,US,3,<NA>,100.0,100.0,100.0,99.9,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
3,University of Oxford,United Kingdom,UK,4,<NA>,100.0,100.0,100.0,90.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings
4,Harvard University,United States,US,5,<NA>,100.0,100.0,99.4,100.0,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,2023 QS World University Rankings

In [18]:
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

output_file = OUTPUT_PATH / "master_dataset.csv"

master_df.to_csv(output_file, index=False)

print(f"Saved Successfully : {output_file}")

Saved Successfully : ..\datasets\final\master_dataset.csv

In [19]:
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38538 entries, 0 to 38537
Data columns (total 25 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   University                            27673 non-null  object
 1   Country                               21136 non-null  object
 2   Country Code                          2920 non-null   object
 3   Rank                                  27548 non-null  object
 4   Overall Score                         19712 non-null  object
 5   Academic Reputation Score             2920 non-null   object
 6   Employer Reputation Score             2918 non-null   object
 7   Faculty Student Score                 2894 non-null   object
 8   Citations per Faculty Score           2891 non-null   object
 9   International Faculty Score           1372 non-null   object
 10  International Students Score          1418 non-null   object
 11  International Research Network Score  1494 non-null   object
 12  Employment Outcomes Score             1474 non-null   object
 13  Sustainability Score                  1398 non-null   object
 14  Student Population                    16713 non-null  object
 15  Students to Staff Ratio               16713 non-null  object
 16  International Students                16711 non-null  object
 17  Female to Male Ratio                  15953 non-null  object
 18  Teaching                              16713 non-null  object
 19  Research Environment                  16713 non-null  object
 20  Research Quality                      16713 non-null  object
 21  Industry Impact                       16713 non-null  object
 22  International Outlook                 16713 non-null  object
 23  Year                                  29176 non-null  object
 24  Source File                           38538 non-null  str
dtypes: object(24), str(1)
memory usage: 7.4+ MB

In [20]:
missing = (
    master_df.isnull()
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

missing.columns = ["Column", "Missing Values"]

missing

                                  Column  Missing Values
0            International Faculty Score           37166
1                   Sustainability Score           37140
2           International Students Score           37120
3              Employment Outcomes Score           37064
4   International Research Network Score           37044
5            Citations per Faculty Score           35647
6                  Faculty Student Score           35644
7              Employer Reputation Score           35620
8              Academic Reputation Score           35618
9                           Country Code           35618
10                  Female to Male Ratio           22585
11                International Students           21827
12                 International Outlook           21825
13                    Student Population           21825
14               Students to Staff Ratio           21825
15                              Teaching           21825
16                  Research Environment           21825
17                      Research Quality           21825
18                       Industry Impact           21825
19                         Overall Score           18826
20                               Country           17402
21                                  Rank           10990
22                            University           10865
23                                  Year            9362
24                           Source File               0

In [21]:
master_df.sample(10)

,University,Country,Country Code,Rank,Overall Score,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,...,Students to Staff Ratio,International Students,Female to Male Ratio,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year,Source File
29115,Universidad Pedagogica y Tecnologica de Colomb...,Colombia,<NA>,2188.0,11.434,<NA>,<NA>,<NA>,<NA>,<NA>,...,18.7,0%,55 : 45,13.9,8.0,6.0,16.4,34.1,2016,THE World University Rankings 2016-2026
38408,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,world-universities
19308,University of Havana,Cuba,<NA>,1364.0,16.4825,<NA>,<NA>,<NA>,<NA>,<NA>,...,10.6,6%,60:40:00,21.4,10.0,7.1,39.5,52.6,2016,THE World University Rankings 2016-2026
5381,<NA>,"Iran, Islamic Republic of",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,QS World University Rankings 2025 (Top global ...
2216,Instituto Tecnológico de Buenos Aires (ITBA),Argentina,AR,791-800,-,9.0,38.8,35.2,1.4,26.7,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2024,2024 QS World University Rankings 1.1 (For qs....
35125,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,world-universities
28453,Universiti Tun Hussein Onn Malaysia (UTHM),Malaysia,<NA>,1526.0,26.874,<NA>,<NA>,<NA>,<NA>,<NA>,...,16.5,7%,45 : 55,23.2,15.3,36.3,30.2,46.6,2016,THE World University Rankings 2016-2026
30713,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,world-universities
23136,Université Libre de Bruxelles,Belgium,<NA>,205.0,58.437,<NA>,<NA>,<NA>,<NA>,<NA>,...,51.7,30%,58:42:00,35.8,45.0,83.5,76.4,89.6,2016,THE World University Rankings 2016-2026
18857,University of Córdoba,Spain,<NA>,913.0,27.17,<NA>,<NA>,<NA>,<NA>,<NA>,...,14.8,9%,56:44:00,18.5,15.7,42.2,36.8,44.4,2016,THE World University Rankings 2016-2026

In [22]:
print("=" * 60)
print("MASTER DATASET SUMMARY")
print("=" * 60)

print(f"Rows              : {master_df.shape[0]}")
print(f"Columns           : {master_df.shape[1]}")
print(f"Duplicate Rows    : {master_df.duplicated().sum()}")

print("\nColumns")

for col in master_df.columns:
    print(f"• {col}")

============================================================
MASTER DATASET SUMMARY
============================================================
Rows              : 38538
Columns           : 25
Duplicate Rows    : 12165

Columns
• University
• Country
• Country Code
• Rank
• Overall Score
• Academic Reputation Score
• Employer Reputation Score
• Faculty Student Score
• Citations per Faculty Score
• International Faculty Score
• International Students Score
• International Research Network Score
• Employment Outcomes Score
• Sustainability Score
• Student Population
• Students to Staff Ratio
• International Students
• Female to Male Ratio
• Teaching
• Research Environment
• Research Quality
• Industry Impact
• International Outlook
• Year
• Source File

In [23]:
print("=" * 60)
print("COLUMN COMPLETENESS")
print("=" * 60)

completeness = pd.DataFrame({
    "Column": master_df.columns,
    "Non-Null Values": master_df.notnull().sum().values,
    "Missing Values": master_df.isnull().sum().values,
    "Completeness (%)": (
        master_df.notnull().mean() * 100
    ).round(2).values
})

completeness.sort_values(
    by="Completeness (%)",
    ascending=False
)

============================================================
COLUMN COMPLETENESS
============================================================

,Column,Non-Null Values,Missing Values,Completeness (%)
24,Source File,38538,0,100.00
23,Year,29176,9362,75.71
0,University,27673,10865,71.81
3,Rank,27548,10990,71.48
1,Country,21136,17402,54.84
4,Overall Score,19712,18826,51.15
22,International Outlook,16713,21825,43.37
21,Industry Impact,16713,21825,43.37
20,Research Quality,16713,21825,43.37
19,Research Environment,16713,21825,43.37
18,Teaching,16713,21825,43.37
15,Students to Staff Ratio,16713,21825,43.37
14,Student Population,16713,21825,43.37
16,International Students,16711,21827,43.36
17,Female to Male Ratio,15953,22585,41.40
5,Academic Reputation Score,2920,35618,7.58
2,Country Code,2920,35618,7.58
6,Employer Reputation Score,2918,35620,7.57
7,Faculty Student Score,2894,35644,7.51
8,Citations per Faculty Score,2891,35647,7.50
11,International Research Network Score,1494,37044,3.88
12,Employment Outcomes Score,1474,37064,3.82
10,International Students Score,1418,37120,3.68
13,Sustainability Score,1398,37140,3.63
9,International Faculty Score,1372,37166,3.56