# Higher Education Data Visualization

## Milestone 1: Data Cleaning and Preparation

### Objective

The objective of this notebook is to demonstrate the data cleaning and preparation process used to integrate multiple higher education datasets into a single analytical dataset.

### Data Sources

- QS World University Rankings
- Times Higher Education (THE)
- OpenAlex
- World Bank Indicators

The final cleaned dataset produced from this process is used for KPI generation and dashboard development.

In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

## Load Source Datasets

The cleaned source datasets generated during the ETL process are loaded for inspection before integration.

In [4]:
qs = pd.read_csv("../data/university_raw_data/qs_master_clean.csv")

the = pd.read_csv("../data/university_raw_data/the_master.csv")

openalex = pd.read_csv("../data/university_raw_data/openalex_master.csv")

worldbank = pd.read_csv("../data/university_raw_data/worldbank_indicators_raw.csv")

final = pd.read_csv("../data/university_cleaned.csv")

## Dataset Overview

The following table shows the number of rows and columns available in each dataset before analysis.

In [5]:
datasets = {
    "QS Rankings": qs,
    "THE Rankings": the,
    "OpenAlex": openalex,
    "World Bank": worldbank,
    "Final Dataset": final,
}

summary = []

for name, df in datasets.items():

    summary.append(
        {
            "Dataset": name,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
        }
    )

pd.DataFrame(summary)

         Dataset   Rows  Columns
0    QS Rankings   7980       15
1   THE Rankings  10051       28
2       OpenAlex   2865       12
3     World Bank   1250       10
4  Final Dataset   9969       61

## Data Quality Assessment

The datasets were inspected for:

- Missing values
- Duplicate records
- Data types

These checks help ensure that the datasets are suitable for integration.

In [6]:
for name, df in datasets.items():

    print("="*60)
    print(name)

    print("\nShape")
    print(df.shape)

    print("\nMissing Values")
    print(df.isnull().sum().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\n")

============================================================
QS Rankings

Shape
(7980, 15)

Missing Values
63346

Duplicate Rows
0


============================================================
THE Rankings

Shape
(10051, 28)

Missing Values
18576

Duplicate Rows
0


============================================================
OpenAlex

Shape
(2865, 12)

Missing Values
5312

Duplicate Rows
0


============================================================
World Bank

Shape
(1250, 10)

Missing Values
1955

Duplicate Rows
0


============================================================
Final Dataset

Shape
(9969, 61)

Missing Values
0

Duplicate Rows
0

## Data Cleaning Performed

The following preprocessing steps were completed before integrating the datasets:

- Removed duplicate records
- Standardized university names
- Standardized country names
- Created a university registry
- Generated university aliases
- Matched universities with OpenAlex
- Applied fuzzy matching for unresolved universities
- Standardized QS ranking datasets
- Standardized THE ranking datasets
- Integrated all datasets into a single analytical dataset

## Final Dataset Validation

The integrated dataset is validated before being used for analysis.

In [7]:
print("Dataset Shape")
print(final.shape)

print("\nDuplicate Rows")
print(final.duplicated().sum())

print("\nDuplicate University-Year Records")
print(
    final.duplicated(
        subset=["university_id","year"]
    ).sum()
)

Dataset Shape
(9969, 61)

Duplicate Rows
0

Duplicate University-Year Records
0

In [8]:
missing = (
    final
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

missing.head(20)

university_id                           0
normalized_name                         0
university_name                         0
country_name                            0
university                              0
country_qs                              0
year                                    0
qs_rank                                 0
qs_score                                0
academic_reputation_score               0
employer_reputation_score               0
faculty_student_score                   0
citations_per_faculty_score             0
international_faculty_score             0
international_students_score            0
international_research_network_score    0
employment_outcomes_score               0
sustainability_score                    0
rank_order                              0
rank                                    0
dtype: int64

In [9]:
final.dtypes

university_id                    str
normalized_name                  str
university_name                  str
country_name                     str
university                       str
                              ...
tertiary_enrollment_ratio    float64
population                   float64
literacy_rate_pct            float64
data_source                      str
download_timestamp_utc           str
Length: 61, dtype: object

In [10]:
final.describe(include="all")

,university_id,normalized_name,university_name,country_name,university,country_qs,year,qs_rank,qs_score,academic_reputation_score,employer_reputation_score,faculty_student_score,citations_per_faculty_score,international_faculty_score,international_students_score,international_research_network_score,employment_outcomes_score,sustainability_score,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,scores_citations_rank,scores_industry_income,scores_industry_income_rank,scores_international_outlook,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited,normalized_name_the,stats_proportion_of_isr,openalex_name,institution_id,works_count,cited_by_count,h_index,i10_index,2yr_mean_citedness,matched_name,score,country_code,gdp_per_capita_usd,education_expenditure_pct_gdp,tertiary_enrollment_ratio,population,literacy_rate_pct,data_source,download_timestamp_utc
count,9969,9969,9969,9969,9969,9969,9969.000000,9969,9969,9969,9969,9969,9969,9969,9969,9969,9969,9969,9.969000e+03,9969,9969,9969,9.969000e+03,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969,9969,9969.000000,9969,9969,9969,9969,9969.0,9969.0,9969,9969,9969,9969,9969.000000,9.969000e+03,9969.000000,9.969000e+03,9969.000000,9969,9969.000000,9969,9969.000000,9969.000000,9969.000000,9.969000e+03,9969.000000,9969,9969
unique,3565,3565,3565,139,1591,105,NaN,698,718,478,497,603,560,527,524,555,450,400,NaN,277,976,302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,2998,NaN,73,77,980,1762,NaN,NaN,975,51,2441,2725,NaN,NaN,NaN,NaN,NaN,402,NaN,91,NaN,NaN,NaN,NaN,NaN,1,1
top,U000001,aalborg university,Aalborg University,United States,University of Dundee,United States,NaN,801-1000,25.2,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,NaN,601–800,Aalborg University,10.3–25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States,"13,510",NaN,1%,55 : 45,Aalborg University,"Accounting & Finance,Art, Performing Arts & De...",NaN,NaN,aalborg university,28%,King Mongkut's University of Technology Thonburi,https://openalex.org/I185261750,NaN,NaN,NaN,NaN,NaN,AKAD University,NaN,USA,NaN,NaN,NaN,NaN,NaN,World Bank API,2026-07-13 06:56:42 UTC
freq,7,7,7,1248,1998,3158,NaN,3013,6570,8493,8496,8515,8539,8673,8588,8756,8516,8746,NaN,7237,6853,7072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7298,6852,NaN,7037,7198,6853,6852,NaN,NaN,6853,9107,2605,1600,NaN,NaN,NaN,NaN,NaN,8966,NaN,6163,NaN,NaN,NaN,NaN,NaN,9969,9969
mean,NaN,NaN,NaN,NaN,NaN,NaN,2020.401244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.293695e+04,NaN,NaN,NaN,1.293695e+04,29.192055,613.510081,26.098937,547.412228,57.443565,638.390711,45.887170,631.929180,53.104885,601.886598,NaN,NaN,16.211445,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,66789.017855,4.844475e+06,423.546895,6.646455e+04,2.888389,NaN,93.140393,NaN,37790.876973,4.854389,73.603547,1.028498e+08,94.978401,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,2.053924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.307234e+04,NaN,NaN,NaN,8.307234e+04,8.833213,257.929086,10.771001,255.473660,14.482598,263.481945,12.379242,262.636611,12.839869,255.999402,NaN,NaN,5.051984,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,84236.192266,9.656238e+06,354.805063,1.030709e+05,1.872422,NaN,0.812531,NaN,17532.960277,0.617556,13.701254,1.744108e+08,2.632349,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+01,NaN,NaN,NaN,1.000000e+01,10.600000,0.000000,7.100000,0.000000,3.400000,0.000000,15.600000,0.000000,14.800000,0.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN,90.000000,NaN,688.566110,0.863943,10.418596,3.865060e+05,58.860001,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.700000e+03,NaN,NaN,NaN,5.700000e+03,27.900000,595.000000,24.600000,518.500000,58.000000,619.000000,43.300000,613.000000,52.000000,583.500000,NaN,NaN,15.600000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,16633.000000,4.455230e+05,196.000000,9.008000e+03,2.116138,NaN,93.103448,NaN,37518.463531,4.890402,74.491310,6.674000e+07,95.250000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.700000e+03,NaN,NaN,NaN,5.700000e+03,27.900000,595.000000,24.600000,518.500000,58.000000,619.000000,43.300000,613.000000,52.000000,583.500000,NaN,NaN,15.600000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,38767.000000,1.645752e+06,337.000000,2.853800e+04,2.802121,NaN,93.103448,NaN,37518.463531,4.890402,74.491310,6.674000e+07,95.250000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.700000e+03,NaN,NaN,NaN,5.700000e+03,27.900000,595.000000,24.600000,518.500000,58.000000,619.000000,43.300000,613.000000,52.000000,583.500000,NaN,NaN,15.600000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,81981.000000,4.761211e+06,535.000000,7.663800e+04,3.438001,NaN,93.103448,NaN,37518.463531,4.890402,74.491310,6.674000e+07,95.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000746e+06,NaN,NaN,NaN,1.000746e+06,99.000000,1900.000000,100.000000,1890.000000,100.000000,1887.000000,100.000000,1904.000000,100.000000,1894.000000,NaN,NaN,114.200000,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,703059.000000,1.431004e+08,3571.000000,1.097327e+06,46.420437,NaN,100.000000,NaN,137781.681659,11.524818,166.389557,1.450936e+09,99.930000,NaN,NaN

## Sample Records

The first five records of the final integrated dataset are shown below.

In [11]:
final.head()

,university_id,normalized_name,university_name,country_name,university,country_qs,year,qs_rank,qs_score,academic_reputation_score,employer_reputation_score,faculty_student_score,citations_per_faculty_score,international_faculty_score,international_students_score,international_research_network_score,employment_outcomes_score,sustainability_score,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,scores_citations_rank,scores_industry_income,scores_industry_income_rank,scores_international_outlook,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited,normalized_name_the,stats_proportion_of_isr,openalex_name,institution_id,works_count,cited_by_count,h_index,i10_index,2yr_mean_citedness,matched_name,score,country_code,gdp_per_capita_usd,education_expenditure_pct_gdp,tertiary_enrollment_ratio,population,literacy_rate_pct,data_source,download_timestamp_utc
0,U000001,aalborg university,Aalborg University,Denmark,Aalborg University,Denmark,2017.0,374,31.5,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,5700.0,601–800,Aalborg University,10.3–25.0,5700.0,27.9,595.0,24.6,518.5,58.0,619.0,43.3,613.0,52.0,583.5,United States,"13,510",15.6,1%,55 : 45,Aalborg University,"Accounting & Finance,Art, Performing Arts & De...",0.0,0.0,aalborg university,28%,Aalborg University,https://openalex.org/I891191580,113379.0,4495056.0,547.0,72656.0,3.121947,AKAD University,93.103448,USA,37518.463531,4.890402,74.491310,66740000.0,95.25,World Bank API,2026-07-13 06:56:42 UTC
1,U000001,aalborg university,Aalborg University,Denmark,Aalborg University,Denmark,2018.0,379,32.2,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,5700.0,601–800,Aalborg University,10.3–25.0,5700.0,27.9,595.0,24.6,518.5,58.0,619.0,43.3,613.0,52.0,583.5,United States,"13,510",15.6,1%,55 : 45,Aalborg University,"Accounting & Finance,Art, Performing Arts & De...",0.0,0.0,aalborg university,28%,Aalborg University,https://openalex.org/I891191580,113379.0,4495056.0,547.0,72656.0,3.121947,AKAD University,93.103448,USA,37518.463531,4.890402,74.491310,66740000.0,95.25,World Bank API,2026-07-13 06:56:42 UTC
2,U000001,aalborg university,Aalborg University,Denmark,Aalborg University,Denmark,2019.0,343,31.6,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,5700.0,601–800,Aalborg University,10.3–25.0,5700.0,27.9,595.0,24.6,518.5,58.0,619.0,43.3,613.0,52.0,583.5,United States,"13,510",15.6,1%,55 : 45,Aalborg University,"Accounting & Finance,Art, Performing Arts & De...",0.0,0.0,aalborg university,28%,Aalborg University,https://openalex.org/I891191580,113379.0,4495056.0,547.0,72656.0,3.121947,AKAD University,93.103448,USA,37518.463531,4.890402,74.491310,66740000.0,95.25,World Bank API,2026-07-13 06:56:42 UTC
3,U000001,aalborg university,Aalborg University,Denmark,Aalborg University,Denmark,2020.0,324,33.0,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,2030.0,201–250,Aalborg University,50.1–53.7,2030.0,28.5,494.0,39.1,221.0,87.1,156.0,48.0,372.0,75.1,231.0,Denmark,"16,340",13.6,15%,55 : 45,Aalborg University,"Education,Politics & International Studies (in...",0.0,0.0,aalborg university,28%,Aalborg University,https://openalex.org/I891191580,113379.0,4495056.0,547.0,72656.0,3.121947,AKAD University,93.103448,DNK,60985.488560,7.385750,82.664330,5831404.0,95.25,World Bank API,2026-07-13 06:56:42 UTC
4,U000001,aalborg university,Aalborg University,Denmark,Aalborg University,Denmark,2021.0,305,34.0,5.7,2.5,100.0,1.4,100.0,1.1,1.0,7.8,1,2030.0,201–250,Aalborg University,50.6–54.2,2030.0,27.6,553.0,38.6,230.0,85.6,195.0,49.1,397.0,74.5,249.0,Denmark,"16,227",13.4,14%,55 : 45,Aalborg University,"Education,Politics & International Studies (in...",0.0,0.0,aalborg university,28%,Aalborg University,https://openalex.org/I891191580,113379.0,4495056.0,547.0,72656.0,3.121947,AKAD University,93.103448,DNK,69340.733492,6.959160,83.982292,5856733.0,95.25,World Bank API,2026-07-13 06:56:42 UTC

## Country Distribution

The following output shows the universities available across different countries.

In [12]:
final["country"].value_counts().head(20)

KeyError: 'country'

## Available Years

The integrated dataset contains university records for multiple years.

In [ ]:
import pandas as pd

df = pd.read_csv("../data/university_cleaned.csv")

print(df.shape)
print(sorted(df["year"].unique()))
print(df["year"].isna().sum())

(7980, 36)
[2017, 2018, 2019, 2020, 2021, 2022, 2024]
0

## Final Summary

The Higher Education datasets from QS Rankings, Times Higher Education, OpenAlex, and World Bank were successfully integrated into a single analytical dataset.

The final dataset contains standardized university information, ranking metrics, research indicators, and country-level educational indicators.

This dataset is ready for KPI generation and dashboard development.

In [ ]:
import pandas as pd

qs = pd.read_csv("../data/processed/qs_master_clean.csv")

print(qs["year"].isna().sum())
print(sorted(qs["year"].unique()))

0
[2017, 2018, 2019, 2020, 2021, 2022, 2024]