# Module 3: KPI Engineering

## Import Libraries

In [23]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\cleaned data\final_cleaned_university_dataset.xls"
)

## Load Cleaned Dataset

In [24]:
df["world_rank_numeric"] = (
    df["world_rank"]
      .astype(str)
      .str.replace("=", "", regex=False)
      .str.replace("+", "", regex=False)
      .str.extract(r"(\d+)", expand=False)
)

df["world_rank_numeric"] = pd.to_numeric(
    df["world_rank_numeric"],
    errors="coerce"
)

## Explore Dataset

In [25]:
df["global_ranking_score"] = (
    (
        df["world_rank_numeric"].max() - df["world_rank_numeric"]
    )
    /
    (
        df["world_rank_numeric"].max() - df["world_rank_numeric"].min()
    )
    * 100
).round(2)

In [26]:
df["research_impact_score"] = (
    (
        df["citations_score"] +
        df["citations_per_faculty"]
    ) / 2
).round(2)

In [27]:
df["faculty_to_student_kpi"] = df["faculty_to_student_ratio"]

## Data Quality Check

In [29]:
[col for col in df.columns if "international" in col.lower()]

['international_students_count',
 'international_student_ratio',
 'country_avg_international_ratio']

In [30]:
df["international_student_percentage_kpi"] = (
    df["international_students_count"]
      .astype(str)
      .str.replace("%", "", regex=False)
      .astype(float)
)

In [31]:
df[[
    "international_students_count",
    "international_student_percentage_kpi"
]].head()

  international_students_count  international_student_percentage_kpi
0                          38%                                  38.0
1                          42%                                  42.0
2                          25%                                  25.0
3                          23%                                  23.0
4                          61%                                  61.0

In [32]:
df["global_ranking_score"] = (
    (
        df["world_rank_numeric"].max() - df["world_rank_numeric"]
    )
    /
    (
        df["world_rank_numeric"].max()
        - df["world_rank_numeric"].min()
    )
) * 100

df["global_ranking_score"] = df["global_ranking_score"].round(2)

In [33]:
df[["world_rank","world_rank_numeric","global_ranking_score"]].head()

  world_rank  world_rank_numeric  global_ranking_score
0          2                   2                100.00
1          3                   3                 99.93
2          4                   4                 99.86
3          5                   5                 99.79
4          6                   6                 99.71

## KPI Engineering

In [34]:
df["research_impact_score"] = (
    df["citations_score"] * 0.6 +
    df["research_output_score"] * 0.4
).round(2)

In [35]:
df["international_students_count"] = (
    df["international_students_count"]
      .astype(str)
      .str.replace("%","",regex=False)
      .astype(float)
)

In [36]:
df[[
    "global_ranking_score",
    "research_impact_score",
    "faculty_to_student_ratio",
    "international_students_count",
    "academic_reputation_score",
    "research_productivity_index"
]].head()

,global_ranking_score,research_impact_score,faculty_to_student_ratio,international_students_count,academic_reputation_score,research_productivity_index
0,100.00,60.18,11.5,38.0,100.0,0.003276
1,99.93,57.96,10.9,42.0,100.0,0.000596
2,99.86,60.40,9.0,25.0,100.0,0.000215
3,99.79,63.94,6.4,23.0,100.0,0.000423
4,99.71,64.80,11.8,61.0,98.3,0.003625

In [37]:
df.to_excel(
    "university_final_dataset.xlsx",
    index=False
)

In [38]:
df.columns.tolist()

['university_id',
 'university_name',
 'year',
 'world_rank',
 'national_rank',
 'overall_score',
 'country',
 'region',
 'city',
 'university_type',
 'academic_reputation_score',
 'employer_reputation_score',
 'citations_score',
 'publications_count',
 'citations_count',
 'citations_per_faculty',
 'h_index',
 'research_output_score',
 'research_productivity_index',
 'subject_field',
 'total_students',
 'international_students_count',
 'international_student_ratio',
 'faculty_count',
 'faculty_to_student_ratio',
 'gender_ratio',
 'female_percentage',
 'male_percentage',
 'degree_level',
 'undergraduate_count',
 'postgraduate_count',
 'country_avg_rank',
 'universities_ranked_count',
 'best_university_rank',
 'country_avg_overall_score',
 'country_avg_academic_reputation',
 'country_avg_citations',
 'country_avg_international_ratio',
 'world_rank_numeric',
 'global_ranking_score',
 'research_impact_score',
 'faculty_to_student_kpi',
 'international_student_percentage_kpi']

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df["university_id"].duplicated().sum()

np.int64(0)

In [41]:
df.duplicated(subset=["university_name", "year"]).sum()

np.int64(0)

In [42]:
print("Shape:", df.shape)
print("Missing values:\n", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate university IDs:", df["university_id"].duplicated().sum())
print("Duplicate University-Year:", df.duplicated(subset=["university_name", "year"]).sum())

Shape: (668, 43)
Missing values:
 0
Duplicate rows: 0
Duplicate university IDs: 0
Duplicate University-Year: 0

In [43]:
df.to_excel(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\university_final_dataset.xlsx",
    index=False
)

print("university_final_dataset.xlsx exported successfully!")

university_final_dataset.xlsx exported successfully!

In [44]:
df["overall_score"] = df["overall_score"].fillna("Not Published")

In [45]:
df["overall_score"] = df["overall_score"].fillna("Not Published")

In [46]:
df["overall_score_numeric"] = pd.to_numeric(
    df["overall_score"],
    errors="coerce"
)

In [47]:
df.to_excel(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\cleaned data\university_final_dataset.xlsx",
    index=False
)

print("✅ university_final_dataset.xlsx exported successfully!")

✅ university_final_dataset.xlsx exported successfully!

In [48]:
import os

os.path.exists(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\cleaned data\university_final_dataset.xlsx"
)

True

In [49]:
df.loc[
    df["world_rank"].isin(["1001-1200", "1201-1400"]),
    ["world_rank", "overall_score"]
].head(10)

    world_rank overall_score
510  1001-1200             -
511  1001-1200             -
512  1001-1200             -
513  1001-1200             -
514  1001-1200             -
515  1001-1200             -
516  1001-1200             -
517  1001-1200             -
518  1001-1200             -
519  1001-1200             -

In [50]:
df["overall_score"].dtype

dtype('O')

In [51]:
(df["overall_score"] == "Not Published").sum()

np.int64(0)

In [52]:
import numpy as np

df["overall_score"] = df["overall_score"].replace("-", np.nan)
df["overall_score"] = df["overall_score"].fillna("Not Published")

In [53]:
df.loc[
    df["world_rank"].isin(["1001-1200", "1201-1400"]),
    ["world_rank", "overall_score"]
].head(10)

    world_rank  overall_score
510  1001-1200  Not Published
511  1001-1200  Not Published
512  1001-1200  Not Published
513  1001-1200  Not Published
514  1001-1200  Not Published
515  1001-1200  Not Published
516  1001-1200  Not Published
517  1001-1200  Not Published
518  1001-1200  Not Published
519  1001-1200  Not Published

## Final Validation

In [54]:
import numpy as np

df["overall_score"] = (
    df["overall_score"]
      .replace("-", np.nan)
      .fillna("Not Published")
)

In [55]:
df[df["world_rank"].isin(["1001-1200", "1201-1400"])][
    ["world_rank", "overall_score"]
].head(10)

    world_rank  overall_score
510  1001-1200  Not Published
511  1001-1200  Not Published
512  1001-1200  Not Published
513  1001-1200  Not Published
514  1001-1200  Not Published
515  1001-1200  Not Published
516  1001-1200  Not Published
517  1001-1200  Not Published
518  1001-1200  Not Published
519  1001-1200  Not Published

In [57]:
df.to_excel(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\cleaned data\university_final_dataset.xlsx",
    index=False
)

print("Export Successful!")

Export Successful!

## Export Final Dataset