In [2]:
import pandas as pd

In [3]:
qs = pd.read_csv("2024 QS World University Rankings 1.1 (For qs.com).csv")

the = pd.read_csv("THE World University Rankings 2016-2026 (1).csv")

In [8]:
qs = qs.rename(columns={'Institution Name':'University'})
the = the.rename(columns={'Name':'University'})

In [12]:
merged.head()

,2024 RANK,2023 RANK,University,Country Code,Country_x,SIZE,FOCUS,RES.,AGE,STATUS,...,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,11.5,38%,48:52:00,97.4820,95.8,100.0,98.0,87.9,97.4,2024
1,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,10.9,42%,49:51:00,98.4575,96.6,100.0,99.0,98.7,97.5,2024
2,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,9.0,25%,51:49:00,97.7905,97.7,99.9,99.4,84.2,90.8,2024
3,5,3,Stanford University,US,United States,L,FC,VH,5,B,...,6.4,23%,47:53:00,97.9720,99.0,97.8,99.6,100.0,87.0,2024
4,6,6=,Imperial College London,UK,United Kingdom,L,FC,VH,5,A,...,11.8,61%,42:58:00,95.0990,90.9,95.5,98.6,90.9,98.3,2024

In [11]:
merged = pd.merge(
    qs,
    the_2024,
    on='University',
    how='inner'
)

In [13]:
merged.shape

(668, 42)

In [14]:
merged.isnull().sum()

2024 RANK                                0
2023 RANK                               28
University                               0
Country Code                             0
Country_x                                0
SIZE                                    10
FOCUS                                    1
RES.                                    24
AGE                                      7
STATUS                                  14
Academic Reputation Score                0
Academic Reputation Rank                 0
Employer Reputation Score                0
Employer Reputation Rank                 0
Faculty Student Score                   10
Faculty Student Rank                    10
Citations per Faculty Score             10
Citations per Faculty Rank              10
International Faculty Score             30
International Faculty Rank              30
International Students Score            16
International Students Rank             16
International Research Network Score     0
International Research Network Rank      0
Employment Outcomes Score               10
Employment Outcomes Rank                10
Sustainability Score                    25
Sustainability Rank                     25
Overall SCORE                            0
Rank                                     0
Country_y                                0
Student Population                       0
Students to Staff Ratio                  0
International Students                   0
Female to Male Ratio                    41
Overall Score                            0
Teaching                                 0
Research Environment                     0
Research Quality                         0
Industry Impact                          0
International Outlook                    0
Year                                     0
dtype: int64

In [15]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 42 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   2024 RANK                             668 non-null    object
 1   2023 RANK                             640 non-null    object
 2   University                            668 non-null    object
 3   Country Code                          668 non-null    object
 4   Country_x                             668 non-null    object
 5   SIZE                                  658 non-null    object
 6   FOCUS                                 667 non-null    object
 7   RES.                                  644 non-null    object
 8   AGE                                   661 non-null    object
 9   STATUS                                654 non-null    object
 10  Academic Reputation Score             668 non-null    object
 11  Academic Reputation Rank              668 non-null    object
 12  Employer Reputation Score             668 non-null    object
 13  Employer Reputation Rank              668 non-null    object
 14  Faculty Student Score                 658 non-null    object
 15  Faculty Student Rank                  658 non-null    object
 16  Citations per Faculty Score           658 non-null    object
 17  Citations per Faculty Rank            658 non-null    object
 18  International Faculty Score           638 non-null    object
 19  International Faculty Rank            638 non-null    object
 20  International Students Score          652 non-null    object
 21  International Students Rank           652 non-null    object
 22  International Research Network Score  668 non-null    object
 23  International Research Network Rank   668 non-null    object
 24  Employment Outcomes Score             658 non-null    object
 25  Employment Outcomes Rank              658 non-null    object
 26  Sustainability Score                  643 non-null    object
 27  Sustainability Rank                   643 non-null    object
 28  Overall SCORE                         668 non-null    object
 29  Rank                                  668 non-null    float64
 30  Country_y                             668 non-null    object
 31  Student Population                    668 non-null    object
 32  Students to Staff Ratio               668 non-null    float64
 33  International Students                668 non-null    object
 34  Female to Male Ratio                  627 non-null    object
 35  Overall Score                         668 non-null    float64
 36  Teaching                              668 non-null    float64
 37  Research Environment                  668 non-null    float64
 38  Research Quality                      668 non-null    float64
 39  Industry Impact                       668 non-null    float64
 40  International Outlook                 668 non-null    float64
 41  Year                                  668 non-null    int64
dtypes: float64(8), int64(1), object(33)
memory usage: 219.3+ KB

In [16]:
merged.to_csv("Merged_University_Rankings.csv", index=False)

In [17]:
merged.duplicated().sum()

np.int64(0)

In [18]:
(merged["Country_x"] == merged["Country_y"]).all()

np.False_

In [19]:
merged[merged["Country_x"] != merged["Country_y"]][["University", "Country_x", "Country_y"]]

,University,Country_x,Country_y
9,Peking University,China (Mainland),China
14,Tsinghua University,China (Mainland),China
25,Zhejiang University,China (Mainland),China
29,Fudan University,China (Mainland),China
30,Shanghai Jiao Tong University,China (Mainland),China
...,...,...,...
547,Saint-Petersburg Mining University,Russia,Russian Federation
603,Mendeleev University of Chemical Technology,Russia,Russian Federation
642,Voronezh State University,Russia,Russian Federation
649,Irkutsk State University,Russia,Russian Federation
652,MIREA - Russian Technological University,Russia,Russian Federation

In [20]:
merged = merged.rename(columns={"Country_x": "Country"})
merged = merged.drop(columns=["Country_y"])

In [21]:
merged.columns

Index(['2024 RANK', '2023 RANK', 'University', 'Country Code', 'Country',
       'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score',
       'Academic Reputation Rank', 'Employer Reputation Score',
       'Employer Reputation Rank', 'Faculty Student Score',
       'Faculty Student Rank', 'Citations per Faculty Score',
       'Citations per Faculty Rank', 'International Faculty Score',
       'International Faculty Rank', 'International Students Score',
       'International Students Rank', 'International Research Network Score',
       'International Research Network Rank', 'Employment Outcomes Score',
       'Employment Outcomes Rank', 'Sustainability Score',
       'Sustainability Rank', 'Overall SCORE', 'Rank', 'Student Population',
       'Students to Staff Ratio', 'International Students',
       'Female to Male Ratio', 'Overall Score', 'Teaching',
       'Research Environment', 'Research Quality', 'Industry Impact',
       'International Outlook', 'Year'],
      dtype='object')

In [22]:
merged.to_csv("Merged_University_Rankings.csv", index=False)

In [23]:
import pandas as pd

df3 = pd.read_csv("A Comprehensive Overview of the Worlds Top 1000 Universities a 14-column dataset (1).csv")
df4 = pd.read_csv("Top 1000 Universities Worldwide.csv")

In [24]:
import os

os.listdir()

['.anaconda',
 '.angular-config.json',
 '.arduinoIDE',
 '.conda',
 '.config',
 '.continuum',
 '.dbus-keyrings',
 '.eclipse',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.lesshst',
 '.matplotlib',
 '.MemuHyperv',
 '.ms-ad',
 '.node_repl_history',
 '.p2',
 '.spyder-py3',
 '.ssh',
 '.thumbnails',
 '.vscode',
 '.vscode-shared',
 '2011_2015_rankings.csv',
 '2024 QS World University Rankings 1.1 (For qs.com).csv',
 '3D Objects',
 'A Comprehensive Overview of the Worlds Top 1000 Universities a 14-column dataset (1).csv',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'BullseyeCoverageError.txt',
 'Contacts',
 'CONTRIBUTING.md',
 'Cookies',
 'Custom_EDA_Summary.html',
 'data_collection script.py',
 'DaVinci Resolve Media',
 'Desktop',
 'Downloads',
 'eclipse-workspace',
 'Emit_Libraries',
 'ev_charging.xlsx',
 'EV_Charging_EDA_Report.html',
 'Favorites',
 'FINALYEAR.PY',
 'Final_University_Dataset.csv',
 'higher education project.ipynb',
 'higher-education-dv',
 'higher_education_project notebook.ipynb',
 'index.html',
 'inittk.ini',
 'inst.ini',
 'IntelGraphicsProfiles',
 'Jedi',
 'Links',
 'Local Settings',
 'matplot.ipynb',
 'Merged_University_Dataset_Phase1.csv',
 'Merged_University_Rankings.csv',
 'mri_best.keras',
 'My Documents',
 'NetHood',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TM.blf',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'numpy.ipynb',
 'nuuid.ini',
 'OneDrive',
 'Pictures',
 'placement.txt',
 'Postman',
 'PrintHood',
 'qs-world-university-rankings-2017-to-2022-V2.csv',
 'Recent',
 'retina.y',
 'Saved Games',
 'scikit_learn_data',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Sweetviz_Report.html',
 'Templates',
 'THE World University Rankings 2016-2026 (1).csv',
 'Top 1000 Universities Worldwide.csv',
 'universities.csv',
 'university_raw_data (1).csv',
 'Untitled Folder',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'useruid.ini',
 'Videos',
 'WPS Cloud Files',
 'WPSDrive']

In [29]:
df3 = df3.rename(columns={
    "Institution": "University",
    "National Rank": "National_Rank",
    "Research Output": "Research_Output",
    "Quality Publications": "Quality_Publications",
    "Citations": "Citations_Count"
})

df4 = df4.rename(columns={
    "University_Name": "University"
})

In [32]:
merged = pd.merge(
    merged,
    df3,
    on="University",
    how="left"
)

In [33]:
merged.shape

(668, 54)

In [34]:
merged = pd.merge(
    merged,
    df4,
    on="University",
    how="left"
)

In [35]:
merged.shape

(668, 72)

In [36]:
merged.head()

,2024 RANK,2023 RANK,University,Country Code,Country_x,SIZE,FOCUS,RES.,AGE,STATUS,...,Postgrad_Students,Faculty_Count,Student_Faculty_Ratio,Research_Output_y,International_Students (%),Tuition_Fee_USD,Acceptance_Rate (%),Graduation_Rate (%),Employability_Rank,QS_Subject_Rank
0,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,8040.0,1824.0,11.5,Very High,38.0,48000.0,21.0,97.0,5.0,5.0
1,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,9585.0,2045.0,10.8,Very High,43.0,45000.0,17.0,96.0,3.0,2.0
2,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,15431.0,2258.0,10.0,Very High,25.0,57261.0,3.0,97.0,4.0,4.0
3,5,3,Stanford University,US,United States,L,FC,VH,5,B,...,9876.0,2875.0,5.9,Very High,23.0,61731.0,4.0,94.0,2.0,3.0
4,6,6=,Imperial College London,UK,United Kingdom,L,FC,VH,5,A,...,10000.0,1735.0,12.1,Very High,60.0,42000.0,14.0,92.0,7.0,6.0

In [37]:
import os

os.listdir()

['.anaconda',
 '.angular-config.json',
 '.arduinoIDE',
 '.conda',
 '.config',
 '.continuum',
 '.dbus-keyrings',
 '.eclipse',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.lesshst',
 '.matplotlib',
 '.MemuHyperv',
 '.ms-ad',
 '.node_repl_history',
 '.p2',
 '.spyder-py3',
 '.ssh',
 '.thumbnails',
 '.vscode',
 '.vscode-shared',
 '2011_2015_rankings.csv',
 '2024 QS World University Rankings 1.1 (For qs.com).csv',
 '3D Objects',
 'A Comprehensive Overview of the Worlds Top 1000 Universities a 14-column dataset (1).csv',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'BullseyeCoverageError.txt',
 'Contacts',
 'CONTRIBUTING.md',
 'Cookies',
 'Custom_EDA_Summary.html',
 'data_collection script.py',
 'DaVinci Resolve Media',
 'Desktop',
 'Downloads',
 'eclipse-workspace',
 'Emit_Libraries',
 'ev_charging.xlsx',
 'EV_Charging_EDA_Report.html',
 'Favorites',
 'FINALYEAR.PY',
 'Final_University_Dataset.csv',
 'higher education project.ipynb',
 'higher-education-dv',
 'higher_education_project notebook.ipynb',
 'index.html',
 'inittk.ini',
 'inst.ini',
 'IntelGraphicsProfiles',
 'Jedi',
 'Links',
 'Local Settings',
 'matplot.ipynb',
 'Merged_University_Dataset_Phase1.csv',
 'Merged_University_Rankings.csv',
 'mri_best.keras',
 'My Documents',
 'NetHood',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TM.blf',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{60b80569-8c78-11f0-aa61-cb135b0a4533}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'numpy.ipynb',
 'nuuid.ini',
 'OneDrive',
 'Pictures',
 'placement.txt',
 'Postman',
 'PrintHood',
 'qs-world-university-rankings-2017-to-2022-V2.csv',
 'Recent',
 'retina.y',
 'Saved Games',
 'scikit_learn_data',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Sweetviz_Report.html',
 'Templates',
 'THE World University Rankings 2016-2026 (1).csv',
 'Top 1000 Universities Worldwide.csv',
 'universities.csv',
 'university_raw_data (1).csv',
 'Untitled Folder',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'useruid.ini',
 'Videos',
 'WPS Cloud Files',
 'WPSDrive']

In [38]:
import pandas as pd

df5 = pd.read_csv("qs-world-university-rankings-2017-to-2022-V2.csv")
df6 = pd.read_csv("universities.csv")

In [43]:
df5 = df5.rename(columns={"university": "University"})

In [45]:
df5.shape

(1300, 15)

In [46]:
df5 = df5[[
    "University",
    "city",
    "region",
    "type",
    "research_output",
    "student_faculty_ratio",
    "faculty_count"
]]

In [47]:
merged = pd.merge(
    merged,
    df5,
    on="University",
    how="left"
)

In [48]:
merged.shape

(668, 78)

In [49]:
df5 = df5.rename(columns={"university": "University"})

In [51]:
merged = pd.merge(
    merged,
    df5,
    on="University",
    how="left"
)

In [52]:
merged.shape

(668, 84)

In [53]:
merged.head()

,2024 RANK,2023 RANK,University,Country Code,Country_x,SIZE,FOCUS,RES.,AGE,STATUS,...,type_x,research_output_x,student_faculty_ratio_x,faculty_count_x,city_y,region_y,type_y,research_output_y,student_faculty_ratio_y,faculty_count_y
0,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,Public,Very high,4.0,"5,800",Cambridge,Europe,Public,Very high,4.0,"5,800"
1,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,Public,Very High,3.0,"6,708",Oxford,Europe,Public,Very High,3.0,"6,708"
2,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,Private,Very High,5.0,"4,646",Cambridge,North America,Private,Very High,5.0,"4,646"
3,5,3,Stanford University,US,United States,L,FC,VH,5,B,...,Private,Very High,3.0,"4,725",Stanford,North America,Private,Very High,3.0,"4,725"
4,6,6=,Imperial College London,UK,United Kingdom,L,FC,VH,5,A,...,Public,Very High,5.0,"8,000",London,Europe,Public,Very High,5.0,"8,000"

In [54]:
merged = pd.merge(
    merged,
    df5,
    on="University",
    how="left"
)

In [55]:
merged.shape

(668, 90)

In [56]:
merged[["University", "city", "region", "type"]].head(10)

                   University          city         region     type
0     University of Cambridge     Cambridge         Europe   Public
1        University of Oxford        Oxford         Europe   Public
2          Harvard University     Cambridge  North America  Private
3         Stanford University      Stanford  North America  Private
4     Imperial College London        London         Europe   Public
5                         UCL        London         Europe   Public
6  University of Pennsylvania  Philadelphia  North America  Private
7          Cornell University        Ithaca  North America  Private
8             Yale University     New Haven  North America  Private
9           Peking University       Beijing           Asia   Public

In [57]:
merged[["city", "region", "type"]].isnull().sum()

city      86
region    56
type      56
dtype: int64

In [58]:
df6 = df6.rename(columns={"name": "University"})

In [60]:
merged = pd.merge(
    merged,
    df6,
    on="University",
    how="left",
    suffixes=("", "_new")
)

In [61]:
merged["city"] = merged["city"].fillna(merged["city_new"])
merged["type"] = merged["type"].fillna(merged["type_new"])

In [62]:
merged.drop(columns=["city_new", "type_new"], inplace=True)

In [63]:
merged[["city", "region", "type"]].isnull().sum()

city      59
region    56
type      56
dtype: int64

In [64]:
merged.to_csv("Merged_University_Dataset_Phase1.csv", index=False)

In [65]:
merged.columns.tolist()

['2024 RANK',
 '2023 RANK',
 'University',
 'Country Code',
 'Country_x',
 'SIZE',
 'FOCUS',
 'RES.',
 'AGE',
 'STATUS',
 'Academic Reputation Score',
 'Academic Reputation Rank',
 'Employer Reputation Score',
 'Employer Reputation Rank',
 'Faculty Student Score',
 'Faculty Student Rank',
 'Citations per Faculty Score',
 'Citations per Faculty Rank',
 'International Faculty Score',
 'International Faculty Rank',
 'International Students Score',
 'International Students Rank',
 'International Research Network Score',
 'International Research Network Rank',
 'Employment Outcomes Score',
 'Employment Outcomes Rank',
 'Sustainability Score',
 'Sustainability Rank',
 'Overall SCORE',
 'Rank',
 'Student Population',
 'Students to Staff Ratio',
 'International Students',
 'Female to Male Ratio',
 'Overall Score',
 'Teaching',
 'Research Environment',
 'Research Quality',
 'Industry Impact',
 'International Outlook',
 'Year',
 'World Rank',
 'Location',
 'National_Rank_x',
 'Quality of Education',
 'Alumni Employment',
 'Quality of Faculty',
 'Research_Output_x',
 'Quality_Publications',
 'Influence',
 'Citations_Count',
 'Score',
 'Latitude',
 'Longitude',
 'Country_y',
 'World_Rank',
 'National_Rank_y',
 'QS_Rank',
 'THE_Rank',
 'ARWU_Rank',
 'Enrollment',
 'Undergrad_Students',
 'Postgrad_Students',
 'Faculty_Count',
 'Student_Faculty_Ratio',
 'Research_Output_y',
 'International_Students (%)',
 'Tuition_Fee_USD',
 'Acceptance_Rate (%)',
 'Graduation_Rate (%)',
 'Employability_Rank',
 'QS_Subject_Rank',
 'city_x',
 'region_x',
 'type_x',
 'research_output_x',
 'student_faculty_ratio_x',
 'faculty_count_x',
 'city_y',
 'region_y',
 'type_y',
 'research_output_y',
 'student_faculty_ratio_y',
 'faculty_count_y',
 'city',
 'region',
 'type',
 'research_output',
 'student_faculty_ratio',
 'faculty_count']

In [66]:
df_2023 = merged.copy()
df_2024 = merged.copy()

In [81]:
merged["Year"].unique()

array([2024])

In [84]:
merged["universities_ranked_count"] = merged.groupby("Country_x")["University"].transform("count")

In [85]:
merged["best_university_rank"] = merged.groupby("Country_x")["Rank"].transform("min")

In [86]:
merged["country_avg_overall_score"] = merged.groupby("Country_x")["Overall Score"].transform("mean")

In [ ]:
merged["Academic Reputation Score"].dtype

In [ ]:
merged["Academic Reputation Score"] = pd.to_numeric(
    merged["Academic Reputation Score"],
    errors="coerce"
)

In [ ]:
merged["Academic Reputation Score"].dtype

In [ ]:
merged["country_avg_rank"] = merged.groupby("Country_x")["Rank"].transform("mean")

In [ ]:
merged["country_avg_citations"] = merged.groupby("Country_x")["Citations_Count"].transform("mean")

In [ ]:
merged["country_avg_international_ratio"] = merged.groupby("Country_x")["International_Students (%)"].transform("mean")

In [ ]:
merged["research_productivity_index"] = (
    merged["Research Quality"] +
    merged["Research Environment"] +
    merged["Industry Impact"]
) / 3

In [ ]:
merged.info()

In [ ]:
merged.insert(
    0,
    "university_id",
    ["U{:04d}".format(i) for i in range(1, len(merged) + 1)]
)

In [ ]:
merged["Female to Male Ratio"].head(10)

In [ ]:
# Split the ratio into three parts
ratio = merged["Female to Male Ratio"].str.split(":", expand=True)

# Create female and male percentage columns
merged["female_percentage"] = pd.to_numeric(ratio[0], errors="coerce")
merged["male_percentage"] = pd.to_numeric(ratio[1], errors="coerce")

In [ ]:
merged[["Female to Male Ratio", "female_percentage", "male_percentage"]].head(10)

In [ ]:
import os

os.listdir()

In [ ]:
df7 = pd.read_csv("2011_2015_rankings.csv")

In [ ]:
df7 = df7.rename(columns={
    "name": "University",
    "subjects_offered": "subject_field",
    "scores_citations": "citations_score",
    "Year": "Year"
})

In [ ]:
merged = pd.merge(
    merged,
    df7,
    on=["University", "Year"],
    how="left"
)

In [ ]:
merged[["subject_field", "citations_score"]].isnull().sum()

In [ ]:
df7 = df7.rename(columns={
    "name": "University",
    "subjects_offered": "subject_field",
    "scores_citations": "citations_score"
})

df7 = df7[["University", "subject_field", "citations_score"]]

# Keep only one record per university
df7 = df7.drop_duplicates(subset="University")

merged = pd.merge(
    merged,
    df7,
    on="University",
    how="left"
)

In [ ]:
merged.columns[-15:]

In [ ]:
merged["subject_field"] = merged["subject_field_x"].combine_first(merged["subject_field_y"])

merged["citations_score"] = merged["citations_score_x"].combine_first(merged["citations_score_y"])

In [ ]:
merged[["subject_field", "citations_score"]].isnull().sum()

In [ ]:
merged.drop(
    columns=[
        "subject_field_x",
        "subject_field_y",
        "citations_score_x",
        "citations_score_y"
    ],
    inplace=True
)

In [ ]:
merged.columns[-10:]

In [ ]:
for col in merged.columns:
    print(col)

In [ ]:
merged["research_output"].unique()

In [ ]:
research_map = {
    "Very High": 100,
    "Very high": 100,
    "High": 75,
    "Medium": 50,
    "Low": 25
}

merged["research_output_score"] = merged["research_output"].map(research_map)

In [ ]:
merged[["research_output", "research_output_score"]].head(10)

In [ ]:
merged.to_csv("Final_University_Dataset.csv", index=False)

In [ ]:
import os

os.listdir()

In [ ]:
merged.to_csv(r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\Final_University_Dataset.csv", index=False)

In [ ]:
missing = merged.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)

In [ ]:
cols_to_drop = [
    "Country_y",
    "World_Rank",
    "National_Rank_y",
    "ARWU_Rank",
    "THE_Rank",
    "QS_Rank",
    "Enrollment",
    "Undergrad_Students",
    "Postgrad_Students",
    "Faculty_Count",
    "Student_Faculty_Ratio",
    "Research_Output_y",
    "International_Students (%)",
    "Tuition_Fee_USD",
    "Acceptance_Rate (%)",
    "Graduation_Rate (%)",
    "Employability_Rank",
    "QS_Subject_Rank"
]

merged.drop(columns=cols_to_drop, inplace=True)

In [ ]:
missing = merged.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)

In [ ]:
for i, col in enumerate(merged.columns, start=1):
    print(f"{i}. {col}")

In [ ]:
merged = pd.merge(
    merged,
    df4[
        [
            "University",
            "Enrollment",
            "Undergrad_Students",
            "Postgrad_Students",
            "Faculty_Count",
            "Student_Faculty_Ratio",
            "Research_Output",
            "International_Students (%)",
            "Tuition_Fee_USD",
            "Acceptance_Rate (%)",
            "Graduation_Rate (%)",
            "Employability_Rank",
            "QS_Subject_Rank",
            "QS_Rank",
            "THE_Rank",
            "ARWU_Rank"
        ]
    ],
    on="University",
    how="left"
)

In [ ]:
merged.columns.tolist()

In [ ]:
missing = merged.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0])

In [ ]:
# Categorical columns
merged["FOCUS"] = merged["FOCUS"].fillna(merged["FOCUS"].mode()[0])
merged["AGE"] = merged["AGE"].fillna(merged["AGE"].mode()[0])
merged["SIZE"] = merged["SIZE"].fillna(merged["SIZE"].mode()[0])
merged["STATUS"] = merged["STATUS"].fillna(merged["STATUS"].mode()[0])

In [ ]:
merged["Employment Outcomes Score"] = pd.to_numeric(
    merged["Employment Outcomes Score"], errors="coerce"
)

merged["Employment Outcomes Score"] = merged["Employment Outcomes Score"].fillna(
    merged["Employment Outcomes Score"].median()
)

In [ ]:
merged["Undergrad_Students"] = merged["Undergrad_Students"].fillna(-1)
merged["Postgrad_Students"] = merged["Postgrad_Students"].fillna(-1)
merged["Faculty_Count"] = merged["Faculty_Count"].fillna(-1)

In [ ]:
import pandas as pd

# Numeric columns
numeric_cols = [
    "World_Rank",
    "National_Rank_y",
    "QS_Rank",
    "THE_Rank",
    "ARWU_Rank",
    "Enrollment",
    "Undergrad_Students",
    "Postgrad_Students",
    "Faculty_Count",
    "Student_Faculty_Ratio",
    "International_Students (%)",
    "Tuition_Fee_USD",
    "Acceptance_Rate (%)",
    "Graduation_Rate (%)",
    "Employability_Rank",
    "QS_Subject_Rank"
]

for col in numeric_cols:
    if col in merged.columns:
        merged[col] = pd.to_numeric(merged[col], errors="coerce")
        merged[col] = merged[col].fillna(-1)

# Categorical column
if "Research_Output_y" in merged.columns:
    merged["Research_Output_y"] = merged["Research_Output_y"].fillna("Unknown")

In [ ]:
for col in merged.columns:
    print(col)

In [ ]:
import pandas as pd

numeric_cols = [
    "World Rank",
    "National_Rank_x",
    "QS_Rank",
    "THE_Rank",
    "ARWU_Rank",
    "Enrollment",
    "Undergrad_Students",
    "Postgrad_Students",
    "Faculty_Count",
    "Student_Faculty_Ratio",
    "International_Students (%)",
    "Tuition_Fee_USD",
    "Acceptance_Rate (%)",
    "Graduation_Rate (%)",
    "Employability_Rank",
    "QS_Subject_Rank"
]

for col in numeric_cols:
    if col in merged.columns:
        merged[col] = pd.to_numeric(merged[col], errors="coerce")
        merged[col] = merged[col].fillna(-1)

# Fill categorical column
merged["Research_Output"] = merged["Research_Output"].fillna("Unknown")

In [ ]:
merged[numeric_cols + ["Research_Output"]].isnull().sum()

In [ ]:
merged.to_csv(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\Final_University_Dataset.csv",
    index=False
)

print("Dataset saved successfully!")

In [ ]:
import pandas as pd

final_df = pd.read_csv(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\Final_University_Dataset.csv"
)

In [ ]:
final_df.shape

In [ ]:
missing = final_df.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0])

In [ ]:
required_columns = [
    "publications_count",
    "h_index",
    "degree_level",
    "undergraduate_count",
    "postgraduate_count",
    "international_student_ratio"
]

for col in required_columns:
    print(col, col in merged.columns)

In [ ]:
import pandas as pd

merged = pd.read_csv(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\Final_University_Dataset.csv"
)

In [ ]:
import os
os.getcwd()

In [ ]:
import os

os.listdir()

In [ ]:
import os

os.listdir(r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data")

In [ ]:
merged = pd.read_csv(
    r"C:\Users\s sai vaishnavi\OneDrive\Desktop\Higher_Education_Project\datasets\processed_data\Final_University_Dataset.csv"
)

In [ ]:
friend = pd.read_csv("university_raw_data (1).csv")

In [ ]:
friend = pd.read_csv("university_raw_data (1).csv", low_memory=False)

In [ ]:
friend.shape

In [ ]:
friend.isnull().sum().sort_values(ascending=False)

In [ ]:
my_cols = set(merged.columns.str.lower())
friend_cols = set(friend.columns.str.lower())

missing = friend_cols - my_cols

print(missing)

In [ ]:
merged.rename(columns={
    "Undergrad_Students":"undergraduate_count",
    "Postgrad_Students":"postgraduate_count",
    "Faculty_Count":"faculty_count",
    "International_Students (%)":"international_student_ratio"
}, inplace=True)

In [ ]:
friend.rename(columns={
    "university_name": "University",
    "year": "Year"
}, inplace=True)

In [ ]:
merged["Year"] = merged["Year"].astype(str)
friend["Year"] = friend["Year"].astype(str)

merged["University"] = merged["University"].str.strip()
friend["University"] = friend["University"].str.strip()

In [ ]:
cols_to_take = [
    "University",
    "Year",
    "publications_count",
    "h_index",
    "degree_level",
    "undergraduate_count",
    "postgraduate_count",
    "international_student_ratio"
]

merged = merged.merge(
    friend[cols_to_take],
    on=["University", "Year"],
    how="left"
)

In [ ]:
merged["Undergrad_Students"] = merged["Undergrad_Students"].fillna(
    merged["undergraduate_count"]
)

merged["Postgrad_Students"] = merged["Postgrad_Students"].fillna(
    merged["postgraduate_count"]
)

In [ ]:
merged.columns.tolist()

In [ ]:
[col for col in merged.columns if "under" in col.lower()]

In [ ]:
[col for col in merged.columns if "post" in col.lower()]

In [ ]:
[col for col in merged.columns if "international" in col.lower()]

In [ ]:
merged["undergraduate_count_x"] = merged["undergraduate_count_x"].fillna(
    merged["undergraduate_count_y"]
)

In [ ]:
merged["postgraduate_count_x"] = merged["postgraduate_count_x"].fillna(
    merged["postgraduate_count_y"]
)

In [ ]:
merged["international_student_ratio_x"] = merged["international_student_ratio_x"].fillna(
    merged["international_student_ratio_y"]
)

In [ ]:
merged.rename(columns={
    "undergraduate_count_x":"undergraduate_count",
    "postgraduate_count_x":"postgraduate_count",
    "international_student_ratio_x":"international_student_ratio"
}, inplace=True)

In [ ]:
merged.drop(columns=[
    "undergraduate_count_y",
    "postgraduate_count_y",
    "international_student_ratio_y"
], inplace=True)

In [ ]:
merged[
    [
        "undergraduate_count",
        "postgraduate_count",
        "international_student_ratio",
        "publications_count",
        "h_index",
        "degree_level"
    ]
].isnull().sum()

In [ ]:
merged.columns[merged.columns == "faculty_count"]

In [ ]:
merged[
    [
        "undergraduate_count",
        "postgraduate_count",
        "international_student_ratio",
        "publications_count",
        "h_index",
        "degree_level"
    ]
].isnull().sum()

In [ ]:
merged.columns.tolist()

In [88]:
merged.columns.tolist()

['2024 RANK',
 '2023 RANK',
 'University',
 'Country Code',
 'Country_x',
 'SIZE',
 'FOCUS',
 'RES.',
 'AGE',
 'STATUS',
 'Academic Reputation Score',
 'Academic Reputation Rank',
 'Employer Reputation Score',
 'Employer Reputation Rank',
 'Faculty Student Score',
 'Faculty Student Rank',
 'Citations per Faculty Score',
 'Citations per Faculty Rank',
 'International Faculty Score',
 'International Faculty Rank',
 'International Students Score',
 'International Students Rank',
 'International Research Network Score',
 'International Research Network Rank',
 'Employment Outcomes Score',
 'Employment Outcomes Rank',
 'Sustainability Score',
 'Sustainability Rank',
 'Overall SCORE',
 'Rank',
 'Student Population',
 'Students to Staff Ratio',
 'International Students',
 'Female to Male Ratio',
 'Overall Score',
 'Teaching',
 'Research Environment',
 'Research Quality',
 'Industry Impact',
 'International Outlook',
 'Year',
 'World Rank',
 'Location',
 'National_Rank_x',
 'Quality of Education',
 'Alumni Employment',
 'Quality of Faculty',
 'Research_Output_x',
 'Quality_Publications',
 'Influence',
 'Citations_Count',
 'Score',
 'Latitude',
 'Longitude',
 'Country_y',
 'World_Rank',
 'National_Rank_y',
 'QS_Rank',
 'THE_Rank',
 'ARWU_Rank',
 'Enrollment',
 'Undergrad_Students',
 'Postgrad_Students',
 'Faculty_Count',
 'Student_Faculty_Ratio',
 'Research_Output_y',
 'International_Students (%)',
 'Tuition_Fee_USD',
 'Acceptance_Rate (%)',
 'Graduation_Rate (%)',
 'Employability_Rank',
 'QS_Subject_Rank',
 'city_x',
 'region_x',
 'type_x',
 'research_output_x',
 'student_faculty_ratio_x',
 'faculty_count_x',
 'city_y',
 'region_y',
 'type_y',
 'research_output_y',
 'student_faculty_ratio_y',
 'faculty_count_y',
 'city',
 'region',
 'type',
 'research_output',
 'student_faculty_ratio',
 'faculty_count',
 'universities_ranked_count',
 'best_university_rank',
 'country_avg_overall_score']

In [89]:
merged[["Country_x","Country_y"]].isnull().sum()

Country_x      0
Country_y    663
dtype: int64

In [90]:
merged[["city","city_x","city_y"]].isnull().sum()

city      59
city_x    86
city_y    86
dtype: int64

In [91]:
merged[["region","region_x","region_y"]].isnull().sum()

region      56
region_x    56
region_y    56
dtype: int64

In [92]:
merged[["faculty_count","faculty_count_x","faculty_count_y"]].isnull().sum()

faculty_count      57
faculty_count_x    57
faculty_count_y    57
dtype: int64

In [93]:
merged[["Country_x","Country_y"]].isnull().sum()

Country_x      0
Country_y    663
dtype: int64

In [94]:
merged[["city","city_x","city_y"]].isnull().sum()

city      59
city_x    86
city_y    86
dtype: int64

In [95]:
merged[["region","region_x","region_y"]].isnull().sum()

region      56
region_x    56
region_y    56
dtype: int64

In [96]:
merged[["faculty_count","faculty_count_x","faculty_count_y"]].isnull().sum()

faculty_count      57
faculty_count_x    57
faculty_count_y    57
dtype: int64

In [97]:
(merged["region"] == merged["region_x"]).value_counts(dropna=False)

True     619
False     56
Name: count, dtype: int64

In [98]:
(merged["region"] == merged["region_y"]).value_counts(dropna=False)

True     619
False     56
Name: count, dtype: int64

In [99]:
(merged["faculty_count"] == merged["faculty_count_x"]).value_counts(dropna=False)

True     618
False     57
Name: count, dtype: int64

In [100]:
(merged["faculty_count"] == merged["faculty_count_y"]).value_counts(dropna=False)

True     618
False     57
Name: count, dtype: int64

In [102]:
merged[["National_Rank_x","National_Rank_y"]].isnull().sum()

National_Rank_x    296
National_Rank_y    663
dtype: int64

In [103]:
merged[["Research_Output_x","Research_Output_y"]].isnull().sum()

Research_Output_x    296
Research_Output_y    663
dtype: int64

In [104]:
merged.duplicated().sum()

np.int64(7)

In [105]:
merged.shape

(675, 93)

In [106]:
merged = merged.drop_duplicates().reset_index(drop=True)

print("New Shape:", merged.shape)

New Shape: (668, 93)

In [107]:
columns_to_drop = [
    "Country_y",
    "city_x", "city_y",
    "region_x", "region_y",
    "type_x", "type_y",
    "faculty_count_x", "faculty_count_y",
    "student_faculty_ratio_x", "student_faculty_ratio_y",
    "National_Rank_y",
    "Research_Output_y"
]

merged = merged.drop(columns=columns_to_drop)

print("Remaining Columns:", len(merged.columns))

Remaining Columns: 80

In [108]:
merged.shape

(668, 80)

In [109]:
merged.columns.tolist()

['2024 RANK',
 '2023 RANK',
 'University',
 'Country Code',
 'Country_x',
 'SIZE',
 'FOCUS',
 'RES.',
 'AGE',
 'STATUS',
 'Academic Reputation Score',
 'Academic Reputation Rank',
 'Employer Reputation Score',
 'Employer Reputation Rank',
 'Faculty Student Score',
 'Faculty Student Rank',
 'Citations per Faculty Score',
 'Citations per Faculty Rank',
 'International Faculty Score',
 'International Faculty Rank',
 'International Students Score',
 'International Students Rank',
 'International Research Network Score',
 'International Research Network Rank',
 'Employment Outcomes Score',
 'Employment Outcomes Rank',
 'Sustainability Score',
 'Sustainability Rank',
 'Overall SCORE',
 'Rank',
 'Student Population',
 'Students to Staff Ratio',
 'International Students',
 'Female to Male Ratio',
 'Overall Score',
 'Teaching',
 'Research Environment',
 'Research Quality',
 'Industry Impact',
 'International Outlook',
 'Year',
 'World Rank',
 'Location',
 'National_Rank_x',
 'Quality of Education',
 'Alumni Employment',
 'Quality of Faculty',
 'Research_Output_x',
 'Quality_Publications',
 'Influence',
 'Citations_Count',
 'Score',
 'Latitude',
 'Longitude',
 'World_Rank',
 'QS_Rank',
 'THE_Rank',
 'ARWU_Rank',
 'Enrollment',
 'Undergrad_Students',
 'Postgrad_Students',
 'Faculty_Count',
 'Student_Faculty_Ratio',
 'International_Students (%)',
 'Tuition_Fee_USD',
 'Acceptance_Rate (%)',
 'Graduation_Rate (%)',
 'Employability_Rank',
 'QS_Subject_Rank',
 'research_output_x',
 'research_output_y',
 'city',
 'region',
 'type',
 'research_output',
 'student_faculty_ratio',
 'faculty_count',
 'universities_ranked_count',
 'best_university_rank',
 'country_avg_overall_score']

In [110]:
merged[["research_output", "research_output_x", "research_output_y"]].isnull().sum()

research_output      56
research_output_x    56
research_output_y    56
dtype: int64

In [111]:
(merged["research_output"] == merged["research_output_x"]).value_counts(dropna=False)

True     612
False     56
Name: count, dtype: int64

In [112]:
(merged["research_output"] == merged["research_output_y"]).value_counts(dropna=False)

True     612
False     56
Name: count, dtype: int64

In [113]:
merged = merged.drop(columns=["research_output_x", "research_output_y"])

In [114]:
merged[["Overall SCORE", "Overall Score"]].head(10)

  Overall SCORE  Overall Score
0          99.2        97.4820
1          98.9        98.4575
2          98.3        97.7905
3          98.1        97.9720
4          97.8        95.0990
5          92.4        88.1145
6          89.4        90.9825
7          89.3        89.5105
8          87.7        94.2010
9          87.0        91.7960

In [115]:
merged[["2024 RANK", "World Rank", "World_Rank", "QS_Rank", "THE_Rank", "ARWU_Rank"]].head(10)

  2024 RANK  World Rank  World_Rank  QS_Rank  THE_Rank  ARWU_Rank
0         2         4.0         5.0      6.0       5.0        4.0
1         3         5.0         2.0      4.0       1.0        6.0
2         4         1.0         4.0      5.0       3.0        1.0
3         5         2.0         3.0      3.0       6.0        2.0
4         6        30.0         6.0      2.0       9.0       23.0
5         9         NaN         9.0      9.0      22.0       15.0
6        12        13.0        16.0     13.0      14.0       14.0
7        13        14.0        15.0     16.0      20.0       12.0
8        16        11.0        14.0     21.0      10.0       11.0
9       =17        92.0        12.0     15.0      13.0       24.0

In [116]:
merged[["Overall SCORE", "Overall Score"]].head(10)

  Overall SCORE  Overall Score
0          99.2        97.4820
1          98.9        98.4575
2          98.3        97.7905
3          98.1        97.9720
4          97.8        95.0990
5          92.4        88.1145
6          89.4        90.9825
7          89.3        89.5105
8          87.7        94.2010
9          87.0        91.7960

In [117]:
merged[[
    "2024 RANK",
    "World Rank",
    "World_Rank",
    "QS_Rank",
    "THE_Rank",
    "ARWU_Rank"
]].head(10)

  2024 RANK  World Rank  World_Rank  QS_Rank  THE_Rank  ARWU_Rank
0         2         4.0         5.0      6.0       5.0        4.0
1         3         5.0         2.0      4.0       1.0        6.0
2         4         1.0         4.0      5.0       3.0        1.0
3         5         2.0         3.0      3.0       6.0        2.0
4         6        30.0         6.0      2.0       9.0       23.0
5         9         NaN         9.0      9.0      22.0       15.0
6        12        13.0        16.0     13.0      14.0       14.0
7        13        14.0        15.0     16.0      20.0       12.0
8        16        11.0        14.0     21.0      10.0       11.0
9       =17        92.0        12.0     15.0      13.0       24.0

In [118]:
merged[["2024 RANK","QS_Rank"]].head(15)

   2024 RANK  QS_Rank
0          2      6.0
1          3      4.0
2          4      5.0
3          5      3.0
4          6      2.0
5          9      9.0
6         12     13.0
7         13     16.0
8         16     21.0
9        =17     15.0
10       =17     25.0
11       =19      NaN
12        21      NaN
13        23      NaN
14        25     14.0

In [119]:
merged[["World Rank","World_Rank"]].head(15)

    World Rank  World_Rank
0          4.0         5.0
1          5.0         2.0
2          1.0         4.0
3          2.0         3.0
4         30.0         6.0
5          NaN         9.0
6         13.0        16.0
7         14.0        15.0
8         11.0        14.0
9         92.0        12.0
10         7.0        13.0
11         NaN         NaN
12        17.0         NaN
13         8.0         NaN
14        98.0        11.0

In [120]:
merged[[
    "2024 RANK",
    "World Rank",
    "World_Rank",
    "QS_Rank",
    "THE_Rank",
    "ARWU_Rank",
    "University",
    "Year"
]].head(20)

,2024 RANK,World Rank,World_Rank,QS_Rank,THE_Rank,ARWU_Rank,University,Year
0,2,4.0,5.0,6.0,5.0,4.0,University of Cambridge,2024
1,3,5.0,2.0,4.0,1.0,6.0,University of Oxford,2024
2,4,1.0,4.0,5.0,3.0,1.0,Harvard University,2024
3,5,2.0,3.0,3.0,6.0,2.0,Stanford University,2024
4,6,30.0,6.0,2.0,9.0,23.0,Imperial College London,2024
5,9,NaN,9.0,9.0,22.0,15.0,UCL,2024
6,12,13.0,16.0,13.0,14.0,14.0,University of Pennsylvania,2024
7,13,14.0,15.0,16.0,20.0,12.0,Cornell University,2024
8,16,11.0,14.0,21.0,10.0,11.0,Yale University,2024
9,=17,92.0,12.0,15.0,13.0,24.0,Peking University,2024
10,=17,7.0,13.0,25.0,4.0,7.0,Princeton University,2024
11,=19,NaN,NaN,NaN,NaN,NaN,The University of Sydney,2024
12,21,17.0,NaN,NaN,NaN,NaN,University of Toronto,2024
13,23,8.0,NaN,NaN,NaN,NaN,Columbia University,2024
14,25,98.0,11.0,14.0,12.0,18.0,Tsinghua University,2024
15,28,16.0,NaN,NaN,NaN,NaN,Johns Hopkins University,2024
16,28,NaN,NaN,NaN,NaN,NaN,The University of Tokyo,2024
17,30,37.0,NaN,NaN,NaN,NaN,McGill University,2024
18,33,NaN,NaN,NaN,NaN,NaN,University of Michigan-Ann Arbor,2024
19,=34,38.0,NaN,NaN,NaN,NaN,University of British Columbia,2024

In [123]:
rename_dict = {
    "University": "university_name",
    "Country_x": "country",
    "Country Code": "country_code",
    "2024 RANK": "world_rank",
    "National_Rank_x": "national_rank",
    "Overall SCORE": "overall_score",
    "Year": "year",

    "Academic Reputation Score": "academic_reputation_score",
    "Academic Reputation Rank": "academic_reputation_rank",

    "Employer Reputation Score": "employer_reputation_score",
    "Employer Reputation Rank": "employer_reputation_rank",

    "Faculty Student Score": "faculty_student_score",
    "Faculty Student Rank": "faculty_student_rank",

    "Citations per Faculty Score": "citations_per_faculty",
    "Citations per Faculty Rank": "citations_per_faculty_rank",

    "International Faculty Score": "international_faculty_score",
    "International Faculty Rank": "international_faculty_rank",

    "International Students Score": "international_students_score",
    "International Students Rank": "international_students_rank",

    "International Research Network Score": "international_research_network_score",
    "International Research Network Rank": "international_research_network_rank",

    "Employment Outcomes Score": "employment_outcomes_score",
    "Employment Outcomes Rank": "employment_outcomes_rank",

    "Sustainability Score": "sustainability_score",
    "Sustainability Rank": "sustainability_rank",

    "Student Population": "total_students",
    "Students to Staff Ratio": "faculty_to_student_ratio",

    "International Students": "international_students_count",

    "Female to Male Ratio": "gender_ratio",

    "Teaching": "teaching_score",
    "Research Environment": "research_environment",
    "Research Quality": "research_quality",
    "Industry Impact": "industry_impact",
    "International Outlook": "international_outlook",

    "World Rank": "cwur_rank",
    "World_Rank": "alternate_world_rank",

    "Quality of Education": "quality_of_education",
    "Alumni Employment": "alumni_employment",
    "Quality of Faculty": "quality_of_faculty",

    "Research_Output_x": "research_output_score",

    "Quality_Publications": "quality_publications",
    "Influence": "influence",

    "Citations_Count": "citations_count",

    "Score": "cwur_score",

    "Latitude": "latitude",
    "Longitude": "longitude",

    "QS_Rank": "qs_rank",
    "THE_Rank": "the_rank",
    "ARWU_Rank": "arwu_rank",

    "Enrollment": "enrollment",

    "Undergrad_Students": "undergraduate_count",
    "Postgrad_Students": "postgraduate_count",

    "Faculty_Count": "faculty_count_dataset",

    "Student_Faculty_Ratio": "student_faculty_ratio_dataset",

    "International_Students (%)": "international_student_ratio",

    "Tuition_Fee_USD": "tuition_fee_usd",

    "Acceptance_Rate (%)": "acceptance_rate",

    "Graduation_Rate (%)": "graduation_rate",

    "Employability_Rank": "employability_rank",

    "QS_Subject_Rank": "qs_subject_rank",

    "city": "city",
    "region": "region",

    "type": "university_type",

    "research_output": "research_output",

    "student_faculty_ratio": "student_faculty_ratio",

    "faculty_count": "faculty_count",

    "universities_ranked_count": "universities_ranked_count",

    "best_university_rank": "best_university_rank",

    "country_avg_overall_score": "country_avg_overall_score"
}

merged.rename(columns=rename_dict, inplace=True)

print("Columns Renamed Successfully!")

Columns Renamed Successfully!

In [125]:
merged[["citations_count", "faculty_count"]].dtypes

citations_count    float64
faculty_count       object
dtype: object

In [126]:
merged["faculty_count"].head(20)

0     5,800
1     6,708
2     4,646
3     4,725
4     8,000
5     7,195
6     5,154
7     2,843
8     5,391
9     5,302
10    1,050
11    3,571
12    9,881
13    7,087
14    6,174
15    4,855
16    4,473
17    3,876
18    7,132
19    6,201
Name: faculty_count, dtype: object

In [127]:
import numpy as np
import pandas as pd

merged["faculty_count"] = (
    merged["faculty_count"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

merged["faculty_count"] = pd.to_numeric(
    merged["faculty_count"],
    errors="coerce"
)

In [128]:
merged["citations_count"] = (
    merged["citations_count"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

merged["citations_count"] = pd.to_numeric(
    merged["citations_count"],
    errors="coerce"
)

In [129]:
merged["research_productivity_index"] = (
    merged["citations_count"] / merged["faculty_count"]
)

merged["research_productivity_index"] = (
    merged["research_productivity_index"]
    .replace([np.inf, -np.inf], np.nan)
)

In [131]:
import pandas as pd
import numpy as np

# Convert faculty_count to numeric
merged["faculty_count"] = (
    merged["faculty_count"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

merged["faculty_count"] = pd.to_numeric(
    merged["faculty_count"],
    errors="coerce"
)

# Convert citations_count to numeric (just to be safe)
merged["citations_count"] = pd.to_numeric(
    merged["citations_count"],
    errors="coerce"
)

# Create Research Productivity Index
merged["research_productivity_index"] = (
    merged["citations_count"] / merged["faculty_count"]
)

# Remove infinite values
merged["research_productivity_index"].replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

C:\Users\s sai vaishnavi\AppData\Local\Temp\ipykernel_1124\3734362020.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged["research_productivity_index"].replace(

In [134]:
merged[["faculty_count","citations_count","research_productivity_index"]].head()

   faculty_count  citations_count  research_productivity_index
0         5800.0             19.0                     0.003276
1         6708.0              4.0                     0.000596
2         4646.0              1.0                     0.000215
3         4725.0              2.0                     0.000423
4         8000.0             29.0                     0.003625

In [133]:
merged["research_productivity_index"] = merged["research_productivity_index"].replace(
    [np.inf, -np.inf],
    np.nan
)

In [135]:
friend = pd.read_csv("university_raw_data (1).csv")

print(friend.shape)

C:\Users\s sai vaishnavi\AppData\Local\Temp\ipykernel_1124\744485980.py:1: DtypeWarning: Columns (1,3,4,5,6,11,12,13,14,15,16,17,18,19,21,22,23,24,25,27,28,30,31,32,33,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  friend = pd.read_csv("university_raw_data (1).csv")

(22118, 39)

In [138]:
friend = pd.read_csv("university_raw_data (1).csv", header=1)

print(friend.shape)
friend.columns.tolist()

(22117, 39)

['Unnamed: 0',
 'university_id',
 'university_name',
 'year',
 'world_rank',
 'national_rank',
 'overall_score',
 'country',
 'region',
 'city',
 'university_type',
 'academic_reputation_score',
 'employer_reputation_score',
 'citations_score',
 'publications_count',
 'citations_count',
 'citations_per_faculty',
 'h_index',
 'research_output_score',
 'research_productivity_index',
 'subject_field',
 'total_students',
 'international_students_count',
 'international_student_ratio',
 'faculty_count',
 'faculty_to_student_ratio',
 'gender_ratio',
 'female_percentage',
 'male_percentage',
 'degree_level',
 'undergraduate_count',
 'postgraduate_count',
 'country_avg_rank',
 'universities_ranked_count',
 'best_university_rank',
 'country_avg_overall_score',
 'country_avg_academic_reputation',
 'country_avg_citations',
 'country_avg_international_ratio']

In [139]:
set(merged["university_name"]).intersection(set(friend["university_name"])).__len__()

649

In [140]:
final = merged.merge(
    friend,
    on=["university_name", "year"],
    how="left",
    suffixes=("", "_friend")
)

In [141]:
final.shape

(668, 120)

In [142]:
for col in friend.columns:

    if col in final.columns and col + "_friend" in final.columns:

        final[col] = final[col].fillna(final[col + "_friend"])

In [144]:
missing = final.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

qs_rank                 656
tuition_fee_usd         656
alternate_world_rank    656
the_rank                656
arwu_rank               656
                       ...
city                      2
faculty_count             1
FOCUS                     1
university_type           1
region                    1
Length: 63, dtype: int64

In [145]:
required_cols = friend.columns.tolist()

final[required_cols].isnull().sum().sort_values(ascending=False)

Unnamed: 0                         19
citations_count                    19
country_avg_citations              19
country_avg_academic_reputation    19
country_avg_rank                   19
postgraduate_count                 19
undergraduate_count                19
degree_level                       19
male_percentage                    19
female_percentage                  19
international_student_ratio        19
subject_field                      19
research_output_score              19
h_index                            19
research_productivity_index        19
publications_count                 19
national_rank                      19
country_avg_international_ratio    19
city                                2
university_type                     1
faculty_count                       1
region                              1
international_students_count        0
citations_score                     0
university_name                     0
year                                0
country_avg_overall_score           0
best_university_rank                0
universities_ranked_count           0
world_rank                          0
overall_score                       0
total_students                      0
country                             0
university_id                       0
citations_per_faculty               0
gender_ratio                        0
faculty_to_student_ratio            0
academic_reputation_score           0
employer_reputation_score           0
dtype: int64

In [146]:
for col in ["city","region","university_type","faculty_count"]:

    if col in final.columns:

        if final[col].dtype == "object":

            final[col] = final[col].fillna(final[col].mode()[0])

        else:

            final[col] = final[col].fillna(final[col].median())

In [147]:
final[required_cols].isnull().sum().sum()

np.int64(342)

In [150]:
final = merged.merge(
    friend_latest,
    on="university_name",
    how="left",
    suffixes=("", "_friend")
)

In [151]:
for col in friend_latest.columns:
    if col in final.columns and col + "_friend" in final.columns:
        final[col] = final[col].fillna(final[col + "_friend"])

In [153]:
final[required_cols].isnull().sum().sort_values(ascending=False)

national_rank                      20
Unnamed: 0                         19
citations_count                    19
country_avg_citations              19
country_avg_academic_reputation    19
country_avg_rank                   19
postgraduate_count                 19
undergraduate_count                19
degree_level                       19
male_percentage                    19
female_percentage                  19
international_student_ratio        19
subject_field                      19
research_output_score              19
h_index                            19
research_productivity_index        19
country_avg_international_ratio    19
publications_count                 19
city                                2
faculty_count                       1
region                              1
university_type                     1
international_students_count        0
overall_score                       0
university_name                     0
year                                0
country_avg_overall_score           0
best_university_rank                0
universities_ranked_count           0
world_rank                          0
country                             0
academic_reputation_score           0
citations_score                     0
university_id                       0
employer_reputation_score           0
gender_ratio                        0
faculty_to_student_ratio            0
total_students                      0
citations_per_faculty               0
dtype: int64

In [154]:
final[required_cols].isnull().sum().sort_values(ascending=False).head(20)

national_rank                      20
Unnamed: 0                         19
citations_count                    19
country_avg_citations              19
country_avg_academic_reputation    19
country_avg_rank                   19
postgraduate_count                 19
undergraduate_count                19
degree_level                       19
male_percentage                    19
female_percentage                  19
international_student_ratio        19
subject_field                      19
research_output_score              19
h_index                            19
research_productivity_index        19
country_avg_international_ratio    19
publications_count                 19
city                                2
faculty_count                       1
dtype: int64

In [160]:
import re

merged["university_name"] = (
    merged["university_name"]
    .str.replace(r"\s*\(.*?\)", "", regex=True)
    .str.strip()
)

friend["university_name"] = (
    friend["university_name"]
    .str.replace(r"\s*\(.*?\)", "", regex=True)
    .str.strip()
)

In [161]:
friend_latest = (
    friend.sort_values("year")
          .drop_duplicates(subset="university_name", keep="last")
)

final = merged.merge(
    friend_latest,
    on="university_name",
    how="left",
    suffixes=("", "_friend")
)

for col in friend_latest.columns:
    if col in final.columns and col + "_friend" in final.columns:
        final[col] = final[col].fillna(final[col + "_friend"])

final.drop(columns=[c for c in final.columns if c.endswith("_friend")], inplace=True)

In [162]:
final["publications_count"].isnull().sum()

np.int64(0)

In [163]:
required_cols = [
    col for col in friend.columns
    if col != "Unnamed: 0"
]

final[required_cols].isnull().sum().sort_values(ascending=False)

national_rank                      1
university_id                      0
undergraduate_count                0
international_student_ratio        0
faculty_count                      0
faculty_to_student_ratio           0
gender_ratio                       0
female_percentage                  0
male_percentage                    0
degree_level                       0
postgraduate_count                 0
total_students                     0
country_avg_rank                   0
universities_ranked_count          0
best_university_rank               0
country_avg_overall_score          0
country_avg_academic_reputation    0
country_avg_citations              0
international_students_count       0
subject_field                      0
university_name                    0
research_productivity_index        0
year                               0
world_rank                         0
overall_score                      0
country                            0
region                             0
city                               0
university_type                    0
academic_reputation_score          0
employer_reputation_score          0
citations_score                    0
publications_count                 0
citations_count                    0
citations_per_faculty              0
h_index                            0
research_output_score              0
country_avg_international_ratio    0
dtype: int64

In [164]:
final[required_cols].isnull().sum().sum()

np.int64(1)

In [165]:
final[final["national_rank"].isna()][
    ["university_name", "country", "world_rank"]
]

         university_name      country world_rank
617  Soongsil University  South Korea  1201-1400

In [166]:
final["national_rank"] = final["national_rank"].fillna(1)

In [167]:
final["national_rank"] = final.groupby("country")["national_rank"].transform(
    lambda x: x.fillna(x.median())
)

In [168]:
final["national_rank"] = final["national_rank"].fillna(1)

In [169]:
final[required_cols].isnull().sum().sum()

np.int64(0)

In [170]:
print(final.shape)
print(final.duplicated().sum())

(668, 92)
0

In [171]:
final.to_csv("final_cleaned_university_dataset.csv", index=False)

print("✅ Final dataset exported successfully!")

✅ Final dataset exported successfully!

In [173]:
final[required_cols].isnull().sum().sum()

np.int64(0)

In [175]:
final.to_csv("final_cleaned_university_dataset.csv", index=False)

In [176]:
final.shape

(668, 38)

In [177]:
final.to_csv("final_cleaned_university_dataset.csv", index=False)

In [178]:
import os

print(os.getcwd())

C:\Users\s sai vaishnavi

In [179]:
check = pd.read_csv("final_cleaned_university_dataset.csv")

check.head()

,university_id,university_name,year,world_rank,national_rank,overall_score,country,region,city,university_type,...,degree_level,undergraduate_count,postgraduate_count,country_avg_rank,universities_ranked_count,best_university_rank,country_avg_overall_score,country_avg_academic_reputation,country_avg_citations,country_avg_international_ratio
0,1,University of Cambridge,2024,2,1.0,99.2,United Kingdom,Europe,Cambridge,Public,...,Undergraduate & Postgraduate,12940.0,8040.0,614.48,69,1.0,50.817341,35.82,38.92,35.29
1,2,University of Oxford,2024,3,2.0,98.9,United Kingdom,Europe,Oxford,Public,...,Undergraduate & Postgraduate,12510.0,9585.0,614.48,69,1.0,50.817341,35.82,38.92,35.29
2,3,Harvard University,2024,4,1.0,98.3,United States,North America,Cambridge,Private,...,Undergraduate & Postgraduate,7153.0,15431.0,647.61,98,2.0,56.843245,29.74,38.11,19.26
3,4,Stanford University,2024,5,2.0,98.1,United States,North America,Stanford,Private,...,Undergraduate & Postgraduate,7087.0,9876.0,647.61,98,2.0,56.843245,29.74,38.11,19.26
4,5,Imperial College London,2024,6,4.0,97.8,United Kingdom,Europe,London,Public,...,Undergraduate & Postgraduate,11000.0,10000.0,614.48,69,1.0,50.817341,35.82,38.92,35.29

In [180]:
check.shape

(668, 38)